
```{r echo = FALSE}
Gloss_data <- read.csv("References/GlossFct.csv", header = TRUE)
Gloss_data$Term = trimws(tolower(Gloss_data$Term))

A1 <- '<a href="#" class="tooltip" style="color:green">*'
A2 <- '*<span style="font-size:8pt">'
A3 <- '</span></a>'

Glossfunction <- function(term){
  temp2 <- which(Gloss_data == trimws(tolower(term)), arr.ind = TRUE)
  ifelse(length(temp2) == 0, return(''), return(Gloss_data[temp2[[1]],2]))
}

Gloss <- function(term){
  return(paste(A1,term,A2,Glossfunction(term),A3, sep=""))
}

```

```{r echo = FALSE}
QUIZ = TRUE
ANIMATION = TRUE
# Switches that control the number of animations in Chapter 6
# Use these for html output
numAnimation = 30     # Section 6.4 Importance Sampling
numAnimation2 = 23    # Section 6.5.1 Hastings Metropolis 
numAnimation3 = 100   # Section 6.5.2 Gibbs
# Use these for pdf output - maybe later

```


```{r echo = FALSE}
B1 <- '<h5 style="text-align: center;"><a id="displayExample.'
B2 <- ' href="javascript:toggleEX(\'toggleExample.'
B3 <- '\',\'displayExample.'
B4a <- '\');"><i><strong>'
B4b <- '</strong></i></a> </h5><div id="toggleExample.'
B5 <- '" style="display: none">'

HideExample <- function(arg1,arg2){
  return(paste(B1,arg1,'"',B2,arg1,B3,arg1,B4a,arg2,B4b,arg1,B5, sep=""))
} 

C1 <- '<h5 style="text-align: center;"><a id="displayCode.'
C2 <- ' href="javascript:togglecode(\'toggleCode.'
C3 <- '\',\'displayCode.'
C4a<- '\');"><i><strong>'
C4b<- '</strong></i></a> </h5><div id="toggleCode.'
C5 <- '" style="display: none">'

HideRCode <- function(arg1,arg2){
  return(paste(C1,arg1,'"',C2,arg1,C3,arg1,C4a,arg2,C4b,arg1,C5, sep=""))
}

# to display R code
ShowCode <- function() {
  return(TRUE)
}

D1 <- '<h5 style="text-align: center;"><a id="displayTheory.'
D2 <- ' href="javascript:toggleTheory(\'toggleTheory.'
D3 <- '\',\'displayTheory.'
D4a<- '\');"><i><strong>'
D4b<- '</strong></i></a> </h5><div id="toggleTheory.'
D5 <- '" style="display: none">'

HideProofTheory <- function(arg1,arg2){
  return(paste(D1,arg1,'"',D2,arg1,C3,arg1,D4a,arg2,D4b,arg1,D5, sep=""))
}

```

