# Appendix E: Conventions for Notation  {#ChapNotationConvention}

*Chapter Preview*. *Loss Data Analytics* serves as a bridge between actuarial problems and methods and widely accepted statistical concepts and tools. Thus, the notation should be consistent with standard usage employed in probability and mathematical statistics. See, for example, [@halperin1965recommended] for a description of one standard.


## General Conventions {#S:General}


- Random variables are denoted by upper-case italicized Roman letters, with $X$ or $Y$ denoting a claim size variable, $N$ a claim count variable, and $S$ an aggregate loss variable. Realizations of random variables are denoted by corresponding lower-case italicized Roman letters, with $x$ or $y$ for claim sizes, $n$ for a claim count, and $s$ for an aggregate loss.
- Probability events are denoted by upper-case Roman letters, such as $\Pr(\mathrm{A})$ for the probability that an outcome in the event ''A'' occurs.
- Cumulative probability functions are denoted by $F(z)$ and probability density functions by the associated lower-case Roman letter: $f(z)$.
- For distributions, parameters are denoted by lower-case Greek letters. A caret or ''hat''  indicates a sample estimate of the corresponding population parameter. For example, $\hat{\beta}$ is an estimate of $\beta$ .
- The arithmetic mean of a set of numbers, say, $x_1, \ldots, x_n$, is usually denoted by $\bar{x}$; the use of $x$, of course, is optional.
- Use upper-case boldface Roman letters to denote a matrix other than a vector. Use lower-case boldface Roman letters to denote a (column) vector. Use a superscript prime ''$\prime$'' for transpose. For example, $\mathbf{x}^{\prime} \mathbf{A} \mathbf{x}$ is a quadratic form.
- Acronyms are to be used sparingly, given the international focus of our audience. Introduce acronyms commonly used in statistical nomenclature but limit the number of acronyms introduced. For example, *pdf* for probability density function is useful but *GS* for Gini statistic is not.



## Abbreviations   {#S:Abbreviations}

Here is a list of abbreviations that we adopt. We italicize these acronyms. For example, we can discuss the goodness of fit in terms of the *AIC* criterion.

$$
\begin{array}{ll}
\hline
AIC & \text{Akaike information criterion} \\
BIC & \text{(Schwarz) Bayesian information criterion} \\
cdf & \text{cumulative distribution function} \\
df & \text{degrees of freedom} \\
iid & \text{independent and identically distributed} \\
GLM & \text{generalized linear model} \\
mle & \text{maximum likelihood estimate/estimator}\\
ols & \text{ordinary least squares} \\
pdf & \text{probability density function} \\
pmf & \text{probability mass function} \\ \hline
\end{array}
$$


## Common Statistical Symbols and Operators  {#S:StatSymbols}

Here is a list of commonly used statistical symbols and operators, including the latex code that we use to generate them (in the parens).

$$
\begin{array}{cl}  \hline
I(\cdot) & \text{binary indicator function (}I\text{). For example, }I(A) \text{ is one if an outcome in event} \\
& \ \ \ \ \  A \text{ occurs and is 0 otherwise.} \\
\Pr(\cdot) & \text{probability }(\backslash{\tt{Pr}}) \\
\mathrm{E}(\cdot)  & {\text{expectation operator }} (\backslash{\tt{mathrm\{E\}}}). {\text{ For example, }} \mathrm{E}(X)=\mathrm{E}~X {\text{ is the }} \\
& \ \ \ \ \ {\text{expected value of the random variable }}X,{\text{ commonly denoted by }}\mu. \\
\mathrm{Var}(\cdot)  & \text{variance operator }(\backslash{\tt{mathrm\{Var\}}}). \text{ For example, } \mathrm{Var}(X)=\mathrm{Var}~X\text{ is the} \\
& \ \ \ \ \  \text{ variance of the random variable } X, \text{commonly denoted by } \sigma^2. \\
\mu_k = \mathrm{E}~X^k & \text{kth moment of the random variable X. For }k\text{=1, use }\mu = \mu_1. \\
\mathrm{Cov}(\cdot,\cdot)  & \text{covariance operator } (\backslash{\tt{mathrm\{Cov\}}}).\text{ For example, } \\
& \ \ \ \ \ \mathrm{Cov}(X,Y)=\mathrm{E}\left\{(X -\mathrm{E}~X)(Y-\mathrm{E}~Y)\right\}  =\mathrm{E}(XY) -(\mathrm{E}~X)(\mathrm{E}~Y)\\
& \ \ \ \ \  \text{ is the covariance between random variables }X\text{ and }Y. \\
\mathrm{E}(X | \cdot)  & \text{conditional expectation operator. For example, }\mathrm{E}(X |Y=y) \text{ is the}\\
& \ \ \ \ \   \text{ conditional expected value of a random variable }X\text{ given that }\\
& \ \ \ \ \   \text{ the random variable }Y\text{ equals y. }\\
\Phi(\cdot) & \text{standard normal cumulative distribution function }(\backslash{\tt{Phi}})\\
\phi(\cdot) & \text{standard normal probability density function }(\backslash{\tt{phi}})\\
\sim & \text{means is distributed as }(\backslash{\tt{sim}}). \text{ For example, }X\sim F \text{ means that the } \\
& \ \ \ \ \  \text{random variable } X \text{ has distribution function }F. \\
se(\hat{\beta}) & \text{standard error of the parameter estimate }\hat{\beta} ~ (\backslash{\tt{hat\{}}\backslash{\tt{beta\}}}), \text{ usually }\\
& \ \ \ \ \  \text{ an estimate of the standard deviation of }\hat{\beta},\text{ which is }\sqrt{Var(\hat{\beta})}. \\
H_0 &  \text{null hypothesis} \\
H_a \text{ or }H_1 & \text{alternative hypothesis} \\
\hline
\end{array}
$$

  
  
## Common Mathematical Symbols and Functions  {#S:Symbols}

Here is a list of commonly used mathematical symbols and functions, including the latex code that we use to generate them (in the parens).
  
$$
\begin{array}{cl}
\hline
\equiv & \text{identity, equivalence }(\backslash\tt{equiv}) \\
\implies     & \text{implies }(\backslash\tt{implies})\\
\iff  & \text{if and only if }(\backslash\tt{iff})\\
\to, \longrightarrow & \text{converges to }(\backslash\tt{to}, \backslash\tt{longrightarrow}) \\
\mathbb{N} & \text{natural numbers }1,2,\ldots ( \backslash\tt{mathbb\{N\}}) \\
\mathbb{R} & \text{real numbers }(\backslash\tt{mathbb\{R\}})\\
\in        & \text{belongs to }(\backslash\tt{in}) \\
\notin     & \text{does not belong to }(\backslash\tt{notin}) \\
\subseteq  & \text{is a subset of }(\backslash\tt{subseteq}) \\
\subset    & \text{is a proper subset of }(\backslash\tt{subset}) \\
\cup       & \text{union  }(\backslash\tt{cup}) \\
\cap       & \text{intersection  }(\backslash\tt{cap}) \\
\emptyset  & \text{empty set }(\backslash\tt{emptyset})  \\
A^{c}      & \text{complement of }A   \\
g*f        & \text{convolution }(g*f)(x)=\int_{-\infty}^{\infty}g(y)f(x-y)dy \\
\exp       & \text{exponential }(\backslash\tt{exp}) \\
\log       & \text{natural logarithm }(\backslash\tt{log})\\
\log_a     & \text{logarithm to the base }a \\
!          & \text{factorial} \\
\text{sgn}(x)    & \text{sign of x}(\tt{sgn}) \\
\lfloor x\rfloor & \text{integer part of x, that is, largest integer }\leq x \\
                 & (\backslash\tt{lfloor}, \backslash\tt{rfloor}) \\
|x|        & \text{absolute value of scalar }x \\
\varGamma(x) & \text{gamma (generalized factorial) function } (\backslash\tt{varGamma}),\\
           & \text{satisfying }\varGamma(x+1)=x\varGamma(x) \\
B(x,y)     & \text{beta function, }\varGamma(x)\varGamma(y)/\varGamma(x+y) \\
\hline
\end{array}
$$




## Further Readings

To make connections to other literatures, see [@abadir2002notation] \url{http://www.janmagnus.nl/misc/notation.zip} for a summary of notation from the econometrics perspective. This reference has a terrific feature that many latex symbols are defined in the article. Further, there is a long history of discussion and debate surrounding actuarial notation; see [@boehm1975thoughts] for one contribution.
