<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics</title>
  <meta name="description" content="Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  <meta name="generator" content="bookdown 0.10 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  <meta name="github-repo" content="https://github.com/openacttexts/Loss-Data-Analytics" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics" />
  
  <meta name="twitter:description" content="Chapter 12 Experience Rating using Bonus-Malus | Loss Data Analytics is an interactive, online, freely available text. - The online version will contain many interactive objects (quizzes, computer demonstrations, interactive graphs, video, and the like) to promote deeper learning. - A subset of the book will be available in pdf format for low-cost printing. - The online text will be available in multiple languages to promote access to a worldwide audience." />
  

<meta name="author" content="An open text authored by the Actuarial Community" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="C-LossReserves.html">
<link rel="next" href="C-DataSystems.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<!-- Mathjax -->
<script type='text/x-mathjax-config'>
		MathJax.Hub.Config({
			extensions: ['tex2jax.js'],
			jax: ['input/TeX', 'output/HTML-CSS'],
			tex2jax: {
				inlineMath: [ ['$','$'], ['\\(','\\)'] ],
				displayMath: [ ['$$','$$'], ['\\[','\\]'] ],
				processEscapes: true
			},
			'HTML-CSS': { availableFonts: ['TeX'] }
		});
</script>

<!-- The following code is for the quizzes -->
<script src="https://surveyjs.azureedge.net/1.0.50/survey.jquery.js"></script>
<link href="https://surveyjs.azureedge.net/1.0.50/survey.css" type="text/css" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.6.4/showdown.min.js"></script>  

<script>
function markdownConverterEWF() {  
//Create showdown markdown converter
var converter = new showdown.Converter();
converter.setOption('ghCompatibleHeaderId', true);
survey
    .onTextMarkdown
    .add(function (survey, options) {
        //convert the mardown text to html
        var str = converter.makeHtml(options.text);
        //remove root paragraphs <p></p>
        str = str.substring(3);
        str = str.substring(0, str.length - 4);
        //set html
        options.html = str;
         MathJax.Hub.Queue(['Typeset',MathJax.Hub, 'options']);
    });  
};
// Quiz Header info
const jsonHeader = { 
    showProgressBar: "bottom",
    showTimerPanel: "none",
    maxTimeToFinishPage: 10000,
    maxTimeToFinish: 25000,
    firstPageIsStarted: true,
    startSurveyText: "Start Quiz" //,
//    title: "Does This Make Sense?"
}
// One and Two question quizzes
function jsonSummary1EWF(json) {  
let jsonEnd1 = { 
completedHtml: 
json["pages"][1]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][1]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][1]["questions"][0]["correctAnswer"]
};  
return jsonEnd1;
};


function jsonSummary2EWF(json) {  
let jsonEnd2 = { 
completedHtml: 
json["pages"][1]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][1]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][1]["questions"][0]["correctAnswer"]
+"<br>"+
json["pages"][2]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][2]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][2]["questions"][0]["correctAnswer"]
};  
return jsonEnd2;
};

// Three, four, and five question quizzes
function jsonSummary3EWF(json) {  
let jsonEnd3 = { 
completedHtml: 
json["pages"][1]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][1]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][1]["questions"][0]["correctAnswer"]
+"<br>"+
json["pages"][2]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][2]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][2]["questions"][0]["correctAnswer"]
+"<br>"+
json["pages"][3]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][3]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][3]["questions"][0]["correctAnswer"]
};  
return jsonEnd3;
};

function jsonSummary4EWF(json) {  
jsonEnd4 = jsonSummary3EWF(json);
jsonEnd4.completedHtml = jsonEnd4.completedHtml +  
"<br>"+
json["pages"][4]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][4]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][4]["questions"][0]["correctAnswer"]
;  
return jsonEnd4;
};

function jsonSummary5EWF(json) {  
jsonEnd5 = jsonSummary4EWF(json);
jsonEnd5.completedHtml = jsonEnd5.completedHtml +  
"<br>"+
json["pages"][5]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][5]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][5]["questions"][0]["correctAnswer"]
;  
return jsonEnd5;
};

function jsonSummary6EWF(json) {  
jsonEnd6 = jsonSummary5EWF(json);
jsonEnd6.completedHtml = jsonEnd6.completedHtml +  
"<br>"+
json["pages"][6]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][6]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][6]["questions"][0]["correctAnswer"]
;  
return jsonEnd6;
};

function jsonSummary7EWF(json) {  
jsonEnd7 = jsonSummary6EWF(json);
jsonEnd7.completedHtml = jsonEnd7.completedHtml +  
"<br>"+
json["pages"][7]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][7]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][7]["questions"][0]["correctAnswer"]
;  
return jsonEnd7;
};

function jsonSummary8EWF(json) {  
jsonEnd8 = jsonSummary7EWF(json);
jsonEnd8.completedHtml = jsonEnd8.completedHtml +  
"<br>"+
json["pages"][8]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][8]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][8]["questions"][0]["correctAnswer"]
;  
return jsonEnd8;
};

function jsonSummary9EWF(json) {  
jsonEnd9 = jsonSummary8EWF(json);
jsonEnd9.completedHtml = jsonEnd9.completedHtml +  
"<br>"+
json["pages"][9]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][9]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][9]["questions"][0]["correctAnswer"]
;  
return jsonEnd9;
};


function jsonSummary10EWF(json) {  
jsonEnd10 = jsonSummary9EWF(json);
jsonEnd10.completedHtml = jsonEnd10.completedHtml +  
"<br>"+
json["pages"][10]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][10]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][10]["questions"][0]["correctAnswer"]
;  
return jsonEnd10;
};


function jsonSummary11EWF(json) {  
jsonEnd11 = jsonSummary10EWF(json);
jsonEnd11.completedHtml = jsonEnd11.completedHtml +  
"<br>"+
json["pages"][11]["questions"][0]["name"]+ "<br>"+
"<i>Question: </i>"+json["pages"][11]["questions"][0]["title"]+"<br>"+
"<i>Answer: </i>"+json["pages"][11]["questions"][0]["correctAnswer"]
;  
return jsonEnd11;
};



</script>  
<!-- This completes the code for the quizzes -->


<!-- Various toggle functions used throughout --> 
<script language="javascript">
function toggle(id1,id2) {
	var ele = document.getElementById(id1); var text = document.getElementById(id2);
	if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Solution";}
		else {ele.style.display = "block"; text.innerHTML = "Hide Solution";}}
function togglecode(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show R Code";}
      else {ele.style.display = "block"; text.innerHTML = "Hide R Code";}}
function toggleEX(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Example";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Example";}}
function toggleTheory(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Theory";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Theory";}}
function toggleQuiz(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Quiz Solution";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Quiz Solution";}}      
</script>

<!-- A few functions for revealing definitions -->
<script language="javascript">
<!--   $( function() {
    $("#tabs").tabs();
  } ); -->

$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
});

$(document).ready(function(){
    $('[data-toggle="popover"]').popover(); 
});
</script>

<script language="javascript">
function openTab(evt, tabName) {
    var i, tabcontent, tablinks;
    tabcontent = document.getElementsByClassName("tabcontent");
    for (i = 0; i < tabcontent.length; i++) {
        tabcontent[i].style.display = "none";
    }
    tablinks = document.getElementsByClassName("tablinks");
    for (i = 0; i < tablinks.length; i++) {
        tablinks[i].className = tablinks[i].className.replace(" active", "");
    }
    document.getElementById(tabName).style.display = "block";
    evt.currentTarget.className += " active";
}

// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>


<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-125587869-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-125587869-1');
</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Loss Data Analytics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i>Acknowledgements</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#reviewers"><i class="fa fa-check"></i>Reviewers</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#for-our-readers"><i class="fa fa-check"></i>For our Readers</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="C-Intro.html"><a href="C-Intro.html"><i class="fa fa-check"></i><b>1</b> Introduction to Loss Data Analytics</a><ul>
<li class="chapter" data-level="1.1" data-path="C-Intro.html"><a href="C-Intro.html#S:Intro"><i class="fa fa-check"></i><b>1.1</b> Relevance of Analytics to Insurance Activities</a><ul>
<li class="chapter" data-level="1.1.1" data-path="C-Intro.html"><a href="C-Intro.html#nature-and-relevance-of-insurance"><i class="fa fa-check"></i><b>1.1.1</b> Nature and Relevance of Insurance</a></li>
<li class="chapter" data-level="1.1.2" data-path="C-Intro.html"><a href="C-Intro.html#what-is-analytics"><i class="fa fa-check"></i><b>1.1.2</b> What is Analytics?</a></li>
<li class="chapter" data-level="1.1.3" data-path="C-Intro.html"><a href="C-Intro.html#S:InsProcesses"><i class="fa fa-check"></i><b>1.1.3</b> Insurance Processes</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="C-Intro.html"><a href="C-Intro.html#S:PredModApps"><i class="fa fa-check"></i><b>1.2</b> Insurance Company Operations</a><ul>
<li class="chapter" data-level="1.2.1" data-path="C-Intro.html"><a href="C-Intro.html#initiating-insurance"><i class="fa fa-check"></i><b>1.2.1</b> Initiating Insurance</a></li>
<li class="chapter" data-level="1.2.2" data-path="C-Intro.html"><a href="C-Intro.html#renewing-insurance"><i class="fa fa-check"></i><b>1.2.2</b> Renewing Insurance</a></li>
<li class="chapter" data-level="1.2.3" data-path="C-Intro.html"><a href="C-Intro.html#claims-and-product-management"><i class="fa fa-check"></i><b>1.2.3</b> Claims and Product Management</a></li>
<li class="chapter" data-level="1.2.4" data-path="C-Intro.html"><a href="C-Intro.html#S:Reserving"><i class="fa fa-check"></i><b>1.2.4</b> Loss Reserving</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="C-Intro.html"><a href="C-Intro.html#S:LGPIF"><i class="fa fa-check"></i><b>1.3</b> Case Study: Wisconsin Property Fund</a><ul>
<li class="chapter" data-level="1.3.1" data-path="C-Intro.html"><a href="C-Intro.html#S:OutComes"><i class="fa fa-check"></i><b>1.3.1</b> Fund Claims Variables: Frequency and Severity</a></li>
<li class="chapter" data-level="1.3.2" data-path="C-Intro.html"><a href="C-Intro.html#S:FundVariables"><i class="fa fa-check"></i><b>1.3.2</b> Fund Rating Variables</a></li>
<li class="chapter" data-level="1.3.3" data-path="C-Intro.html"><a href="C-Intro.html#fund-operations"><i class="fa fa-check"></i><b>1.3.3</b> Fund Operations</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="C-Intro.html"><a href="C-Intro.html#Intro-further-reading-and-resources"><i class="fa fa-check"></i><b>1.4</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html"><i class="fa fa-check"></i><b>2</b> Frequency Modeling</a><ul>
<li class="chapter" data-level="2.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:frequency-distributions"><i class="fa fa-check"></i><b>2.1</b> Frequency Distributions</a><ul>
<li class="chapter" data-level="2.1.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:how-frequency-augments-severity-information"><i class="fa fa-check"></i><b>2.1.1</b> How Frequency Augments Severity Information</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:basic-frequency-distributions"><i class="fa fa-check"></i><b>2.2</b> Basic Frequency Distributions</a><ul>
<li class="chapter" data-level="2.2.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:foundations"><i class="fa fa-check"></i><b>2.2.1</b> Foundations</a></li>
<li class="chapter" data-level="2.2.2" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:generating-functions"><i class="fa fa-check"></i><b>2.2.2</b> Moment and Probability Generating Functions</a></li>
<li class="chapter" data-level="2.2.3" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:important-frequency-distributions"><i class="fa fa-check"></i><b>2.2.3</b> Important Frequency Distributions</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:the-a-b-0-class"><i class="fa fa-check"></i><b>2.3</b> The (a, b, 0) Class</a></li>
<li class="chapter" data-level="2.4" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:estimating-frequency-distributions"><i class="fa fa-check"></i><b>2.4</b> Estimating Frequency Distributions</a><ul>
<li class="chapter" data-level="2.4.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:parameter-estimation"><i class="fa fa-check"></i><b>2.4.1</b> Parameter Estimation</a></li>
<li class="chapter" data-level="2.4.2" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:frequency-distributions-mle"><i class="fa fa-check"></i><b>2.4.2</b> Frequency Distributions MLE</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:other-frequency-distributions"><i class="fa fa-check"></i><b>2.5</b> Other Frequency Distributions</a><ul>
<li class="chapter" data-level="2.5.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:zero-truncation-or-modification"><i class="fa fa-check"></i><b>2.5.1</b> Zero Truncation or Modification</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:mixture-distributions"><i class="fa fa-check"></i><b>2.6</b> Mixture Distributions</a></li>
<li class="chapter" data-level="2.7" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:goodness-of-fit"><i class="fa fa-check"></i><b>2.7</b> Goodness of Fit</a></li>
<li class="chapter" data-level="2.8" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:exercises"><i class="fa fa-check"></i><b>2.8</b> Exercises</a></li>
<li class="chapter" data-level="2.9" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#Freq-further-reading-and-resources"><i class="fa fa-check"></i><b>2.9</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="2.9.1" data-path="C-Frequency-Modeling.html"><a href="C-Frequency-Modeling.html#S:rcode"><i class="fa fa-check"></i><b>2.9.1</b> TS 2.A. R Code for Plots</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="C-Severity.html"><a href="C-Severity.html"><i class="fa fa-check"></i><b>3</b> Modeling Loss Severity</a><ul>
<li class="chapter" data-level="3.1" data-path="C-Severity.html"><a href="C-Severity.html#S:BasicQuantities"><i class="fa fa-check"></i><b>3.1</b> Basic Distributional Quantities</a><ul>
<li class="chapter" data-level="3.1.1" data-path="C-Severity.html"><a href="C-Severity.html#S:Chap3Moments"><i class="fa fa-check"></i><b>3.1.1</b> Moments</a></li>
<li class="chapter" data-level="3.1.2" data-path="C-Severity.html"><a href="C-Severity.html#quantiles"><i class="fa fa-check"></i><b>3.1.2</b> Quantiles</a></li>
<li class="chapter" data-level="3.1.3" data-path="C-Severity.html"><a href="C-Severity.html#moment-generating-function"><i class="fa fa-check"></i><b>3.1.3</b> Moment Generating Function</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="C-Severity.html"><a href="C-Severity.html#S:ContinuousDistn"><i class="fa fa-check"></i><b>3.2</b> Continuous Distributions for Modeling Loss Severity</a><ul>
<li class="chapter" data-level="3.2.1" data-path="C-Severity.html"><a href="C-Severity.html#S:Loss:Gamma"><i class="fa fa-check"></i><b>3.2.1</b> Gamma Distribution</a></li>
<li class="chapter" data-level="3.2.2" data-path="C-Severity.html"><a href="C-Severity.html#pareto-distribution"><i class="fa fa-check"></i><b>3.2.2</b> Pareto Distribution</a></li>
<li class="chapter" data-level="3.2.3" data-path="C-Severity.html"><a href="C-Severity.html#S:LS:Weibull"><i class="fa fa-check"></i><b>3.2.3</b> Weibull Distribution</a></li>
<li class="chapter" data-level="3.2.4" data-path="C-Severity.html"><a href="C-Severity.html#the-generalized-beta-distribution-of-the-second-kind"><i class="fa fa-check"></i><b>3.2.4</b> The Generalized Beta Distribution of the Second Kind</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="C-Severity.html"><a href="C-Severity.html#MethodsCreation"><i class="fa fa-check"></i><b>3.3</b> Methods of Creating New Distributions</a><ul>
<li class="chapter" data-level="3.3.1" data-path="C-Severity.html"><a href="C-Severity.html#functions-of-random-variables-and-their-distributions"><i class="fa fa-check"></i><b>3.3.1</b> Functions of Random Variables and their Distributions</a></li>
<li class="chapter" data-level="3.3.2" data-path="C-Severity.html"><a href="C-Severity.html#multiplication-by-a-constant"><i class="fa fa-check"></i><b>3.3.2</b> Multiplication by a Constant</a></li>
<li class="chapter" data-level="3.3.3" data-path="C-Severity.html"><a href="C-Severity.html#raising-to-a-power"><i class="fa fa-check"></i><b>3.3.3</b> Raising to a Power</a></li>
<li class="chapter" data-level="3.3.4" data-path="C-Severity.html"><a href="C-Severity.html#exponentiation"><i class="fa fa-check"></i><b>3.3.4</b> Exponentiation</a></li>
<li class="chapter" data-level="3.3.5" data-path="C-Severity.html"><a href="C-Severity.html#finite-mixtures"><i class="fa fa-check"></i><b>3.3.5</b> Finite Mixtures</a></li>
<li class="chapter" data-level="3.3.6" data-path="C-Severity.html"><a href="C-Severity.html#continuous-mixtures"><i class="fa fa-check"></i><b>3.3.6</b> Continuous Mixtures</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="C-Severity.html"><a href="C-Severity.html#S:CoverageModifications"><i class="fa fa-check"></i><b>3.4</b> Coverage Modifications</a><ul>
<li class="chapter" data-level="3.4.1" data-path="C-Severity.html"><a href="C-Severity.html#S:PolicyDeduct"><i class="fa fa-check"></i><b>3.4.1</b> Policy Deductibles</a></li>
<li class="chapter" data-level="3.4.2" data-path="C-Severity.html"><a href="C-Severity.html#S:PolicyLimits"><i class="fa fa-check"></i><b>3.4.2</b> Policy Limits</a></li>
<li class="chapter" data-level="3.4.3" data-path="C-Severity.html"><a href="C-Severity.html#coinsurance-and-inflation"><i class="fa fa-check"></i><b>3.4.3</b> Coinsurance and Inflation</a></li>
<li class="chapter" data-level="3.4.4" data-path="C-Severity.html"><a href="C-Severity.html#S:Chap3Reinsurance"><i class="fa fa-check"></i><b>3.4.4</b> Reinsurance</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="C-Severity.html"><a href="C-Severity.html#S:MaxLikeEstimation"><i class="fa fa-check"></i><b>3.5</b> Maximum Likelihood Estimation</a><ul>
<li class="chapter" data-level="3.5.1" data-path="C-Severity.html"><a href="C-Severity.html#maximum-likelihood-estimators-for-complete-data"><i class="fa fa-check"></i><b>3.5.1</b> Maximum Likelihood Estimators for Complete Data</a></li>
<li class="chapter" data-level="3.5.2" data-path="C-Severity.html"><a href="C-Severity.html#S:Loss:MLEModified"><i class="fa fa-check"></i><b>3.5.2</b> Maximum Likelihood Estimators using Modified Data</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="C-Severity.html"><a href="C-Severity.html#LM-further-reading-and-resources"><i class="fa fa-check"></i><b>3.6</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html"><i class="fa fa-check"></i><b>4</b> Model Selection and Estimation</a><ul>
<li class="chapter" data-level="4.1" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:MS:NonParInf"><i class="fa fa-check"></i><b>4.1</b> Nonparametric Inference</a><ul>
<li class="chapter" data-level="4.1.1" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#nonparametric-estimation"><i class="fa fa-check"></i><b>4.1.1</b> Nonparametric Estimation</a></li>
<li class="chapter" data-level="4.1.2" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:MS:ToolsModelSelection"><i class="fa fa-check"></i><b>4.1.2</b> Tools for Model Selection and Diagnostics</a></li>
<li class="chapter" data-level="4.1.3" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#starting-values"><i class="fa fa-check"></i><b>4.1.3</b> Starting Values</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:MS:ModelSelection"><i class="fa fa-check"></i><b>4.2</b> Model Selection</a><ul>
<li class="chapter" data-level="4.2.1" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#iterative-model-selection"><i class="fa fa-check"></i><b>4.2.1</b> Iterative Model Selection</a></li>
<li class="chapter" data-level="4.2.2" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#model-selection-based-on-a-training-dataset"><i class="fa fa-check"></i><b>4.2.2</b> Model Selection Based on a Training Dataset</a></li>
<li class="chapter" data-level="4.2.3" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#model-selection-based-on-a-test-dataset"><i class="fa fa-check"></i><b>4.2.3</b> Model Selection Based on a Test Dataset</a></li>
<li class="chapter" data-level="4.2.4" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#model-selection-based-on-cross-validation"><i class="fa fa-check"></i><b>4.2.4</b> Model Selection Based on Cross-Validation</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:MS:ModifiedData"><i class="fa fa-check"></i><b>4.3</b> Estimation using Modified Data</a><ul>
<li class="chapter" data-level="4.3.1" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#parametric-estimation-using-modified-data"><i class="fa fa-check"></i><b>4.3.1</b> Parametric Estimation using Modified Data</a></li>
<li class="chapter" data-level="4.3.2" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#nonparametric-estimation-using-modified-data"><i class="fa fa-check"></i><b>4.3.2</b> Nonparametric Estimation using Modified Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:MS:BayesInference"><i class="fa fa-check"></i><b>4.4</b> Bayesian Inference</a><ul>
<li class="chapter" data-level="4.4.1" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:IntroBayes"><i class="fa fa-check"></i><b>4.4.1</b> Introduction to Bayesian Inference</a></li>
<li class="chapter" data-level="4.4.2" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#bayesian-model"><i class="fa fa-check"></i><b>4.4.2</b> Bayesian Model</a></li>
<li class="chapter" data-level="4.4.3" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#bayesian-inference"><i class="fa fa-check"></i><b>4.4.3</b> Bayesian Inference</a></li>
<li class="chapter" data-level="4.4.4" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#S:ConjugateDistributions"><i class="fa fa-check"></i><b>4.4.4</b> Conjugate Distributions</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="C-ModelSelection.html"><a href="C-ModelSelection.html#MS:further-reading-and-resources"><i class="fa fa-check"></i><b>4.5</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html"><i class="fa fa-check"></i><b>5</b> Aggregate Loss Models</a><ul>
<li class="chapter" data-level="5.1" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#individual-risk-model"><i class="fa fa-check"></i><b>5.2</b> Individual Risk Model</a></li>
<li class="chapter" data-level="5.3" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#collective-risk-model"><i class="fa fa-check"></i><b>5.3</b> Collective Risk Model</a><ul>
<li class="chapter" data-level="5.3.1" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#moments-and-distribution"><i class="fa fa-check"></i><b>5.3.1</b> Moments and Distribution</a></li>
<li class="chapter" data-level="5.3.2" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#stop-loss-insurance"><i class="fa fa-check"></i><b>5.3.2</b> Stop-loss Insurance</a></li>
<li class="chapter" data-level="5.3.3" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#analytic-results"><i class="fa fa-check"></i><b>5.3.3</b> Analytic Results</a></li>
<li class="chapter" data-level="5.3.4" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#tweedie-distribution"><i class="fa fa-check"></i><b>5.3.4</b> Tweedie Distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#computing-the-aggregate-claims-distribution"><i class="fa fa-check"></i><b>5.4</b> Computing the Aggregate Claims Distribution</a><ul>
<li class="chapter" data-level="5.4.1" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#recursive-method"><i class="fa fa-check"></i><b>5.4.1</b> Recursive Method</a></li>
<li class="chapter" data-level="5.4.2" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#simulation"><i class="fa fa-check"></i><b>5.4.2</b> Simulation</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#effects-of-coverage-modifications"><i class="fa fa-check"></i><b>5.5</b> Effects of Coverage Modifications</a><ul>
<li class="chapter" data-level="5.5.1" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#impact-of-exposure-on-frequency"><i class="fa fa-check"></i><b>5.5.1</b> Impact of Exposure on Frequency</a></li>
<li class="chapter" data-level="5.5.2" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#S:MS:DedImpactClmFreq"><i class="fa fa-check"></i><b>5.5.2</b> Impact of Deductibles on Claim Frequency</a></li>
<li class="chapter" data-level="5.5.3" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#impact-of-policy-modifications-on-aggregate-claims"><i class="fa fa-check"></i><b>5.5.3</b> Impact of Policy Modifications on Aggregate Claims</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#AL-further-reading-and-resources"><i class="fa fa-check"></i><b>5.6</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="" data-path="C-AggLossModels.html"><a href="C-AggLossModels.html#ts-5.a.1.-individual-risk-model-properties"><i class="fa fa-check"></i>TS 5.A.1. Individual Risk Model Properties</a></li>
<li><a href="C-AggLossModels.html#ts-5.a.2.-relationship-between-probability-generating-functions-of-x_i-and-x_it">TS 5.A.2. Relationship Between Probability Generating Functions of <span class="math inline">\(X_i\)</span> and <span class="math inline">\(X_i^T\)</span></a></li>
<li><a href="C-AggLossModels.html#ts-5.a.3.-example-5.3.8-moment-generating-function-of-aggregate-loss-s_n">TS 5.A.3. Example 5.3.8 Moment Generating Function of Aggregate Loss <span class="math inline">\(S_N\)</span></a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="C-Simulation.html"><a href="C-Simulation.html"><i class="fa fa-check"></i><b>6</b> Simulation and Resampling</a><ul>
<li class="chapter" data-level="6.1" data-path="C-Simulation.html"><a href="C-Simulation.html#S:SimulationFundamentals"><i class="fa fa-check"></i><b>6.1</b> Simulation Fundamentals</a><ul>
<li class="chapter" data-level="6.1.1" data-path="C-Simulation.html"><a href="C-Simulation.html#generating-independent-uniform-observations"><i class="fa fa-check"></i><b>6.1.1</b> Generating Independent Uniform Observations</a></li>
<li class="chapter" data-level="6.1.2" data-path="C-Simulation.html"><a href="C-Simulation.html#S:InverseTransform"><i class="fa fa-check"></i><b>6.1.2</b> Inverse Transform Method</a></li>
<li class="chapter" data-level="6.1.3" data-path="C-Simulation.html"><a href="C-Simulation.html#simulation-precision"><i class="fa fa-check"></i><b>6.1.3</b> Simulation Precision</a></li>
<li class="chapter" data-level="6.1.4" data-path="C-Simulation.html"><a href="C-Simulation.html#S:SimulationStatInference"><i class="fa fa-check"></i><b>6.1.4</b> Simulation and Statistical Inference</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="C-Simulation.html"><a href="C-Simulation.html#S:Bootstrap"><i class="fa fa-check"></i><b>6.2</b> Bootstrapping and Resampling</a><ul>
<li class="chapter" data-level="6.2.1" data-path="C-Simulation.html"><a href="C-Simulation.html#bootstrap-foundations"><i class="fa fa-check"></i><b>6.2.1</b> Bootstrap Foundations</a></li>
<li class="chapter" data-level="6.2.2" data-path="C-Simulation.html"><a href="C-Simulation.html#bootstrap-precision-bias-standard-deviation-and-mse"><i class="fa fa-check"></i><b>6.2.2</b> Bootstrap Precision: Bias, Standard Deviation, and MSE</a></li>
<li class="chapter" data-level="6.2.3" data-path="C-Simulation.html"><a href="C-Simulation.html#confidence-intervals"><i class="fa fa-check"></i><b>6.2.3</b> Confidence Intervals</a></li>
<li class="chapter" data-level="6.2.4" data-path="C-Simulation.html"><a href="C-Simulation.html#S:ParametricBootStrap"><i class="fa fa-check"></i><b>6.2.4</b> Parametric Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="C-Simulation.html"><a href="C-Simulation.html#S:CrossValidation"><i class="fa fa-check"></i><b>6.3</b> Cross-Validation</a><ul>
<li class="chapter" data-level="6.3.1" data-path="C-Simulation.html"><a href="C-Simulation.html#k-fold-cross-validation"><i class="fa fa-check"></i><b>6.3.1</b> k-Fold Cross-Validation</a></li>
<li class="chapter" data-level="6.3.2" data-path="C-Simulation.html"><a href="C-Simulation.html#leave-one-out-cross-validation"><i class="fa fa-check"></i><b>6.3.2</b> Leave-One-Out Cross-Validation</a></li>
<li class="chapter" data-level="6.3.3" data-path="C-Simulation.html"><a href="C-Simulation.html#cross-validation-and-bootstrap"><i class="fa fa-check"></i><b>6.3.3</b> Cross-Validation and Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="C-Simulation.html"><a href="C-Simulation.html#S:ImportanceSampling"><i class="fa fa-check"></i><b>6.4</b> Importance Sampling</a></li>
<li class="chapter" data-level="6.5" data-path="C-Simulation.html"><a href="C-Simulation.html#S:MCMC"><i class="fa fa-check"></i><b>6.5</b> Monte Carlo Markov Chain (MCMC)</a><ul>
<li class="chapter" data-level="6.5.1" data-path="C-Simulation.html"><a href="C-Simulation.html#hastings-metropolis"><i class="fa fa-check"></i><b>6.5.1</b> Hastings Metropolis</a></li>
<li class="chapter" data-level="6.5.2" data-path="C-Simulation.html"><a href="C-Simulation.html#gibbs-sampler"><i class="fa fa-check"></i><b>6.5.2</b> Gibbs sampler</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="C-Simulation.html"><a href="C-Simulation.html#Simulation:further-reading-and-resources"><i class="fa fa-check"></i><b>6.6</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="6.6.1" data-path="C-Simulation.html"><a href="C-Simulation.html#ts-6.a.-bootstrap-applications-in-predictive-modeling"><i class="fa fa-check"></i><b>6.6.1</b> TS 6.A. Bootstrap Applications in Predictive Modeling</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html"><i class="fa fa-check"></i><b>7</b> Premium Foundations</a><ul>
<li class="chapter" data-level="7.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:IntroductionRatemaking"><i class="fa fa-check"></i><b>7.1</b> Introduction to Ratemaking</a></li>
<li class="chapter" data-level="7.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:AggRateMaking"><i class="fa fa-check"></i><b>7.2</b> Aggregate Ratemaking Methods</a><ul>
<li class="chapter" data-level="7.2.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:PurePremium"><i class="fa fa-check"></i><b>7.2.1</b> Pure Premium Method</a></li>
<li class="chapter" data-level="7.2.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:LossRatio"><i class="fa fa-check"></i><b>7.2.2</b> Loss Ratio Method</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:PricingPrinciples"><i class="fa fa-check"></i><b>7.3</b> Pricing Principles</a><ul>
<li class="chapter" data-level="7.3.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#premium-principles"><i class="fa fa-check"></i><b>7.3.1</b> Premium Principles</a></li>
<li class="chapter" data-level="7.3.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#properties-of-premium-principles"><i class="fa fa-check"></i><b>7.3.2</b> Properties of Premium Principles</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:HeterogeneousRisks"><i class="fa fa-check"></i><b>7.4</b> Heterogeneous Risks</a><ul>
<li class="chapter" data-level="7.4.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:ExposureToRisk"><i class="fa fa-check"></i><b>7.4.1</b> Exposure to Risk</a></li>
<li class="chapter" data-level="7.4.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:RatingFactors"><i class="fa fa-check"></i><b>7.4.2</b> Rating Factors</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:TrendDevelopment"><i class="fa fa-check"></i><b>7.5</b> Development and Trending</a><ul>
<li class="chapter" data-level="7.5.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#exposures-and-premiums"><i class="fa fa-check"></i><b>7.5.1</b> Exposures and Premiums</a></li>
<li class="chapter" data-level="7.5.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#losses-claims-and-payments"><i class="fa fa-check"></i><b>7.5.2</b> Losses, Claims, and Payments</a></li>
<li class="chapter" data-level="7.5.3" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:CompareMethods"><i class="fa fa-check"></i><b>7.5.3</b> Comparing Pure Premium and Loss Ratio Methods</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#S:GiniStatistic"><i class="fa fa-check"></i><b>7.6</b> Selecting a Premium</a><ul>
<li class="chapter" data-level="7.6.1" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#classic-lorenz-curve"><i class="fa fa-check"></i><b>7.6.1</b> Classic Lorenz Curve</a></li>
<li class="chapter" data-level="7.6.2" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#performance-curve-and-a-gini-statistic"><i class="fa fa-check"></i><b>7.6.2</b> Performance Curve and a Gini Statistic</a></li>
<li class="chapter" data-level="7.6.3" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#out-of-sample-validation"><i class="fa fa-check"></i><b>7.6.3</b> Out-of-Sample Validation</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#further-resources-and-contributors"><i class="fa fa-check"></i><b>7.7</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="" data-path="C-PremiumFoundations.html"><a href="C-PremiumFoundations.html#ts-7.a.-rate-regulation"><i class="fa fa-check"></i>TS 7.A. Rate Regulation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="C-RiskClass.html"><a href="C-RiskClass.html"><i class="fa fa-check"></i><b>8</b> Risk Classification</a><ul>
<li class="chapter" data-level="8.1" data-path="C-RiskClass.html"><a href="C-RiskClass.html#S:RC:Introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="C-RiskClass.html"><a href="C-RiskClass.html#S:RC:PoissonRegression"><i class="fa fa-check"></i><b>8.2</b> Poisson Regression Model</a><ul>
<li class="chapter" data-level="8.2.1" data-path="C-RiskClass.html"><a href="C-RiskClass.html#S:RC:Need.Poi.reg"><i class="fa fa-check"></i><b>8.2.1</b> Need for Poisson Regression</a></li>
<li class="chapter" data-level="8.2.2" data-path="C-RiskClass.html"><a href="C-RiskClass.html#poisson-regression"><i class="fa fa-check"></i><b>8.2.2</b> Poisson Regression</a></li>
<li class="chapter" data-level="8.2.3" data-path="C-RiskClass.html"><a href="C-RiskClass.html#incorporating-exposure"><i class="fa fa-check"></i><b>8.2.3</b> Incorporating Exposure</a></li>
<li class="chapter" data-level="8.2.4" data-path="C-RiskClass.html"><a href="C-RiskClass.html#exercises-3"><i class="fa fa-check"></i><b>8.2.4</b> Exercises</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="C-RiskClass.html"><a href="C-RiskClass.html#S:CatVarMultiTarriff"><i class="fa fa-check"></i><b>8.3</b> Categorical Variables and Multiplicative Tariff</a><ul>
<li class="chapter" data-level="8.3.1" data-path="C-RiskClass.html"><a href="C-RiskClass.html#rating-factors-and-tariff"><i class="fa fa-check"></i><b>8.3.1</b> Rating Factors and Tariff</a></li>
<li class="chapter" data-level="8.3.2" data-path="C-RiskClass.html"><a href="C-RiskClass.html#multiplicative-tariff-model"><i class="fa fa-check"></i><b>8.3.2</b> Multiplicative Tariff Model</a></li>
<li class="chapter" data-level="8.3.3" data-path="C-RiskClass.html"><a href="C-RiskClass.html#poisson-regression-for-multiplicative-tariff"><i class="fa fa-check"></i><b>8.3.3</b> Poisson Regression for Multiplicative Tariff</a></li>
<li class="chapter" data-level="8.3.4" data-path="C-RiskClass.html"><a href="C-RiskClass.html#numerical-examples"><i class="fa fa-check"></i><b>8.3.4</b> Numerical Examples</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="C-RiskClass.html"><a href="C-RiskClass.html#RC:further-reading-and-resources"><i class="fa fa-check"></i><b>8.4</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="" data-path="C-RiskClass.html"><a href="C-RiskClass.html#ts-8.a.-estimating-poisson-regression-models"><i class="fa fa-check"></i>TS 8.A. Estimating Poisson Regression Models</a></li>
<li class="chapter" data-level="" data-path="C-RiskClass.html"><a href="C-RiskClass.html#ts-8.b.-selecting-rating-factors"><i class="fa fa-check"></i>TS 8.B. Selecting Rating Factors</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="C-Credibility.html"><a href="C-Credibility.html"><i class="fa fa-check"></i><b>9</b> Experience Rating Using Credibility Theory</a><ul>
<li class="chapter" data-level="9.1" data-path="C-Credibility.html"><a href="C-Credibility.html#introduction-to-applications-of-credibility-theory"><i class="fa fa-check"></i><b>9.1</b> Introduction to Applications of Credibility Theory</a></li>
<li class="chapter" data-level="9.2" data-path="C-Credibility.html"><a href="C-Credibility.html#limited-fluctuation-credibility"><i class="fa fa-check"></i><b>9.2</b> Limited Fluctuation Credibility</a><ul>
<li class="chapter" data-level="9.2.1" data-path="C-Credibility.html"><a href="C-Credibility.html#S:frequency"><i class="fa fa-check"></i><b>9.2.1</b> Full Credibility for Claim Frequency</a></li>
<li class="chapter" data-level="9.2.2" data-path="C-Credibility.html"><a href="C-Credibility.html#full-credibility-for-aggregate-losses-and-pure-premium"><i class="fa fa-check"></i><b>9.2.2</b> Full Credibility for Aggregate Losses and Pure Premium</a></li>
<li class="chapter" data-level="9.2.3" data-path="C-Credibility.html"><a href="C-Credibility.html#full-credibility-for-severity"><i class="fa fa-check"></i><b>9.2.3</b> Full Credibility for Severity</a></li>
<li class="chapter" data-level="9.2.4" data-path="C-Credibility.html"><a href="C-Credibility.html#partial-credibility"><i class="fa fa-check"></i><b>9.2.4</b> Partial Credibility</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="C-Credibility.html"><a href="C-Credibility.html#buhlmann-credibility"><i class="fa fa-check"></i><b>9.3</b> Bühlmann Credibility</a><ul>
<li class="chapter" data-level="9.3.1" data-path="C-Credibility.html"><a href="C-Credibility.html#S:EPV-VHM-Z"><i class="fa fa-check"></i><b>9.3.1</b> Credibility Z, <em>EPV</em>, and <em>VHM</em></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="C-Credibility.html"><a href="C-Credibility.html#buhlmann-straub-credibility"><i class="fa fa-check"></i><b>9.4</b> Bühlmann-Straub Credibility</a></li>
<li class="chapter" data-level="9.5" data-path="C-Credibility.html"><a href="C-Credibility.html#bayesian-inference-and-buhlmann-credibility"><i class="fa fa-check"></i><b>9.5</b> Bayesian Inference and Bühlmann Credibility</a><ul>
<li class="chapter" data-level="9.5.1" data-path="C-Credibility.html"><a href="C-Credibility.html#gamma-poisson-model"><i class="fa fa-check"></i><b>9.5.1</b> Gamma-Poisson Model</a></li>
<li class="chapter" data-level="9.5.2" data-path="C-Credibility.html"><a href="C-Credibility.html#beta-binomial-model"><i class="fa fa-check"></i><b>9.5.2</b> Beta-Binomial Model</a></li>
<li class="chapter" data-level="9.5.3" data-path="C-Credibility.html"><a href="C-Credibility.html#exact-credibility"><i class="fa fa-check"></i><b>9.5.3</b> Exact Credibility</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="C-Credibility.html"><a href="C-Credibility.html#estimating-credibility-parameters"><i class="fa fa-check"></i><b>9.6</b> Estimating Credibility Parameters</a><ul>
<li class="chapter" data-level="9.6.1" data-path="C-Credibility.html"><a href="C-Credibility.html#full-credibility-standard-for-limited-fluctuation-credibility"><i class="fa fa-check"></i><b>9.6.1</b> Full Credibility Standard for Limited Fluctuation Credibility</a></li>
<li class="chapter" data-level="9.6.2" data-path="C-Credibility.html"><a href="C-Credibility.html#nonparametric-estimation-for-buhlmann-and-buhlmann-straub-models"><i class="fa fa-check"></i><b>9.6.2</b> Nonparametric Estimation for Bühlmann and Bühlmann-Straub Models</a></li>
<li class="chapter" data-level="9.6.3" data-path="C-Credibility.html"><a href="C-Credibility.html#semiparametric-estimation-for-buhlmann-and-buhlmann-straub-models"><i class="fa fa-check"></i><b>9.6.3</b> Semiparametric Estimation for Bühlmann and Bühlmann-Straub Models</a></li>
<li class="chapter" data-level="9.6.4" data-path="C-Credibility.html"><a href="C-Credibility.html#balancing-credibility-estimators"><i class="fa fa-check"></i><b>9.6.4</b> Balancing Credibility Estimators</a></li>
</ul></li>
<li class="chapter" data-level="9.7" data-path="C-Credibility.html"><a href="C-Credibility.html#Cred-further-reading-and-resources"><i class="fa fa-check"></i><b>9.7</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="C-PortMgt.html"><a href="C-PortMgt.html"><i class="fa fa-check"></i><b>10</b> Insurance Portfolio Management including Reinsurance</a><ul>
<li class="chapter" data-level="10.1" data-path="C-PortMgt.html"><a href="C-PortMgt.html#introduction-to-insurance-portfolios"><i class="fa fa-check"></i><b>10.1</b> Introduction to Insurance Portfolios</a></li>
<li class="chapter" data-level="10.2" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:Tails"><i class="fa fa-check"></i><b>10.2</b> Tails of Distributions</a><ul>
<li class="chapter" data-level="10.2.1" data-path="C-PortMgt.html"><a href="C-PortMgt.html#classification-based-on-moments"><i class="fa fa-check"></i><b>10.2.1</b> Classification Based on Moments</a></li>
<li class="chapter" data-level="10.2.2" data-path="C-PortMgt.html"><a href="C-PortMgt.html#comparison-based-on-limiting-tail-behavior"><i class="fa fa-check"></i><b>10.2.2</b> Comparison Based on Limiting Tail Behavior</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:RiskMeasure"><i class="fa fa-check"></i><b>10.3</b> Risk Measures</a><ul>
<li class="chapter" data-level="10.3.1" data-path="C-PortMgt.html"><a href="C-PortMgt.html#coherent-risk-measures"><i class="fa fa-check"></i><b>10.3.1</b> Coherent Risk Measures</a></li>
<li class="chapter" data-level="10.3.2" data-path="C-PortMgt.html"><a href="C-PortMgt.html#value-at-risk"><i class="fa fa-check"></i><b>10.3.2</b> Value-at-Risk</a></li>
<li class="chapter" data-level="10.3.3" data-path="C-PortMgt.html"><a href="C-PortMgt.html#tail-value-at-risk"><i class="fa fa-check"></i><b>10.3.3</b> Tail Value-at-Risk</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:Reinsurance"><i class="fa fa-check"></i><b>10.4</b> Reinsurance</a><ul>
<li class="chapter" data-level="10.4.1" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:ProportionalRe"><i class="fa fa-check"></i><b>10.4.1</b> Proportional Reinsurance</a></li>
<li class="chapter" data-level="10.4.2" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:NonProportionalRe"><i class="fa fa-check"></i><b>10.4.2</b> Non-Proportional Reinsurance</a></li>
<li class="chapter" data-level="10.4.3" data-path="C-PortMgt.html"><a href="C-PortMgt.html#S:AdditionalRe"><i class="fa fa-check"></i><b>10.4.3</b> Additional Reinsurance Treaties</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="C-PortMgt.html"><a href="C-PortMgt.html#further-resources-and-contributors-1"><i class="fa fa-check"></i><b>10.5</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="C-LossReserves.html"><a href="C-LossReserves.html"><i class="fa fa-check"></i><b>11</b> Loss Reserving</a><ul>
<li class="chapter" data-level="11.1" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:motivation"><i class="fa fa-check"></i><b>11.1</b> Motivation</a><ul>
<li class="chapter" data-level="11.1.1" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:claim-types"><i class="fa fa-check"></i><b>11.1.1</b> Closed, IBNR, and RBNS Claims</a></li>
<li class="chapter" data-level="11.1.2" data-path="C-LossReserves.html"><a href="C-LossReserves.html#why-reserving"><i class="fa fa-check"></i><b>11.1.2</b> Why Reserving?</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:Data"><i class="fa fa-check"></i><b>11.2</b> Loss Reserve Data</a><ul>
<li class="chapter" data-level="11.2.1" data-path="C-LossReserves.html"><a href="C-LossReserves.html#from-micro-to-macro"><i class="fa fa-check"></i><b>11.2.1</b> From Micro to Macro</a></li>
<li class="chapter" data-level="11.2.2" data-path="C-LossReserves.html"><a href="C-LossReserves.html#run-off-triangles"><i class="fa fa-check"></i><b>11.2.2</b> Run-off Triangles</a></li>
<li class="chapter" data-level="11.2.3" data-path="C-LossReserves.html"><a href="C-LossReserves.html#loss-reserve-notation"><i class="fa fa-check"></i><b>11.2.3</b> Loss Reserve Notation</a></li>
<li class="chapter" data-level="11.2.4" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:Rcode"><i class="fa fa-check"></i><b>11.2.4</b> R Code to Summarize Loss Reserve Data</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:Chain-ladder"><i class="fa fa-check"></i><b>11.3</b> The Chain-Ladder</a><ul>
<li class="chapter" data-level="11.3.1" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:DeterministicCL"><i class="fa fa-check"></i><b>11.3.1</b> The Deterministic Chain-Ladder</a></li>
<li class="chapter" data-level="11.3.2" data-path="C-LossReserves.html"><a href="C-LossReserves.html#macks-distribution-free-chain-ladder-model"><i class="fa fa-check"></i><b>11.3.2</b> Mack’s Distribution-Free Chain-Ladder Model</a></li>
<li class="chapter" data-level="11.3.3" data-path="C-LossReserves.html"><a href="C-LossReserves.html#r-code-for-chain-ladder-predictions"><i class="fa fa-check"></i><b>11.3.3</b> R code for Chain-Ladder Predictions</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="C-LossReserves.html"><a href="C-LossReserves.html#S:GLMs"><i class="fa fa-check"></i><b>11.4</b> GLMs and Bootstrap for Loss Reserves</a><ul>
<li class="chapter" data-level="11.4.1" data-path="C-LossReserves.html"><a href="C-LossReserves.html#model-specification"><i class="fa fa-check"></i><b>11.4.1</b> Model Specification</a></li>
<li class="chapter" data-level="11.4.2" data-path="C-LossReserves.html"><a href="C-LossReserves.html#model-estimation-and-prediction"><i class="fa fa-check"></i><b>11.4.2</b> Model Estimation and Prediction</a></li>
<li class="chapter" data-level="11.4.3" data-path="C-LossReserves.html"><a href="C-LossReserves.html#bootstrap"><i class="fa fa-check"></i><b>11.4.3</b> Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="C-LossReserves.html"><a href="C-LossReserves.html#LossRe:further-reading-and-resources"><i class="fa fa-check"></i><b>11.5</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html"><i class="fa fa-check"></i><b>12</b> Experience Rating using Bonus-Malus</a><ul>
<li class="chapter" data-level="12.1" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#S:ERBM:Intro"><i class="fa fa-check"></i><b>12.1</b> Introduction</a></li>
<li class="chapter" data-level="12.2" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#S:ERBM:NCD"><i class="fa fa-check"></i><b>12.2</b> NCD System in Several Countries</a><ul>
<li class="chapter" data-level="12.2.1" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#ncd-system-in-malaysia"><i class="fa fa-check"></i><b>12.2.1</b> NCD System in Malaysia</a></li>
<li class="chapter" data-level="12.2.2" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#ncd-system-in-other-countries"><i class="fa fa-check"></i><b>12.2.2</b> NCD System in Other Countries</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#S:ERBM:BMS"><i class="fa fa-check"></i><b>12.3</b> BMS and Markov Chain Model</a><ul>
<li class="chapter" data-level="12.3.1" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#transition-probability"><i class="fa fa-check"></i><b>12.3.1</b> Transition Probability</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#S:ERBM:StatDist"><i class="fa fa-check"></i><b>12.4</b> BMS and Stationary Distribution</a><ul>
<li class="chapter" data-level="12.4.1" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#stationary-distribution"><i class="fa fa-check"></i><b>12.4.1</b> Stationary Distribution</a></li>
<li class="chapter" data-level="12.4.2" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#r-program-for-stationary-distribution"><i class="fa fa-check"></i><b>12.4.2</b> R Program for Stationary Distribution</a></li>
<li class="chapter" data-level="12.4.3" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#premium-evolution"><i class="fa fa-check"></i><b>12.4.3</b> Premium Evolution</a></li>
<li class="chapter" data-level="12.4.4" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#r-program-for-premium-evolution"><i class="fa fa-check"></i><b>12.4.4</b> R Program for Premium Evolution</a></li>
<li class="chapter" data-level="12.4.5" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#convergence-rate"><i class="fa fa-check"></i><b>12.4.5</b> Convergence Rate</a></li>
<li class="chapter" data-level="12.4.6" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#r-program-for-convergence-rate"><i class="fa fa-check"></i><b>12.4.6</b> R Program for Convergence Rate</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#S:PremRtg"><i class="fa fa-check"></i><b>12.5</b> BMS and Premium Rating</a><ul>
<li class="chapter" data-level="12.5.1" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#premium-rating"><i class="fa fa-check"></i><b>12.5.1</b> Premium Rating</a></li>
<li class="chapter" data-level="12.5.2" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#frequency-model-poisson-and-negative-binomial-regressions"><i class="fa fa-check"></i><b>12.5.2</b> Frequency Model – Poisson and Negative Binomial Regressions</a></li>
<li class="chapter" data-level="12.5.3" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#premium-rating-with-bonus-malus-data"><i class="fa fa-check"></i><b>12.5.3</b> Premium Rating with Bonus-Malus Data</a></li>
<li class="chapter" data-level="12.5.4" data-path="C-BonusMalus.html"><a href="C-BonusMalus.html#premium-rating-without-bonus-malus-data"><i class="fa fa-check"></i><b>12.5.4</b> Premium Rating without Bonus-Malus Data</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="C-DataSystems.html"><a href="C-DataSystems.html"><i class="fa fa-check"></i><b>13</b> Data and Systems</a><ul>
<li class="chapter" data-level="13.1" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data"><i class="fa fa-check"></i><b>13.1</b> Data</a><ul>
<li class="chapter" data-level="13.1.1" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-types-and-sources"><i class="fa fa-check"></i><b>13.1.1</b> Data Types and Sources</a></li>
<li class="chapter" data-level="13.1.2" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-structures-and-storage"><i class="fa fa-check"></i><b>13.1.2</b> Data Structures and Storage</a></li>
<li class="chapter" data-level="13.1.3" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-quality"><i class="fa fa-check"></i><b>13.1.3</b> Data Quality</a></li>
<li class="chapter" data-level="13.1.4" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-cleaning"><i class="fa fa-check"></i><b>13.1.4</b> Data Cleaning</a></li>
</ul></li>
<li class="chapter" data-level="13.2" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-analysis-preliminaries"><i class="fa fa-check"></i><b>13.2</b> Data Analysis Preliminaries</a><ul>
<li class="chapter" data-level="13.2.1" data-path="C-DataSystems.html"><a href="C-DataSystems.html#S:process"><i class="fa fa-check"></i><b>13.2.1</b> Data Analysis Process</a></li>
<li class="chapter" data-level="13.2.2" data-path="C-DataSystems.html"><a href="C-DataSystems.html#exploratory-versus-confirmatory"><i class="fa fa-check"></i><b>13.2.2</b> Exploratory versus Confirmatory</a></li>
<li class="chapter" data-level="13.2.3" data-path="C-DataSystems.html"><a href="C-DataSystems.html#supervised-versus-unsupervised"><i class="fa fa-check"></i><b>13.2.3</b> Supervised versus Unsupervised</a></li>
<li class="chapter" data-level="13.2.4" data-path="C-DataSystems.html"><a href="C-DataSystems.html#parametric-versus-nonparametric"><i class="fa fa-check"></i><b>13.2.4</b> Parametric versus Nonparametric</a></li>
<li class="chapter" data-level="13.2.5" data-path="C-DataSystems.html"><a href="C-DataSystems.html#S:expred"><i class="fa fa-check"></i><b>13.2.5</b> Explanation versus Prediction</a></li>
<li class="chapter" data-level="13.2.6" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-modeling-versus-algorithmic-modeling"><i class="fa fa-check"></i><b>13.2.6</b> Data Modeling versus Algorithmic Modeling</a></li>
<li class="chapter" data-level="13.2.7" data-path="C-DataSystems.html"><a href="C-DataSystems.html#big-data-analysis"><i class="fa fa-check"></i><b>13.2.7</b> Big Data Analysis</a></li>
<li class="chapter" data-level="13.2.8" data-path="C-DataSystems.html"><a href="C-DataSystems.html#reproducible-analysis"><i class="fa fa-check"></i><b>13.2.8</b> Reproducible Analysis</a></li>
<li class="chapter" data-level="13.2.9" data-path="C-DataSystems.html"><a href="C-DataSystems.html#ethical-issues"><i class="fa fa-check"></i><b>13.2.9</b> Ethical Issues</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="C-DataSystems.html"><a href="C-DataSystems.html#data-analysis-techniques"><i class="fa fa-check"></i><b>13.3</b> Data Analysis Techniques</a><ul>
<li class="chapter" data-level="13.3.1" data-path="C-DataSystems.html"><a href="C-DataSystems.html#exploratory-techniques"><i class="fa fa-check"></i><b>13.3.1</b> Exploratory Techniques</a></li>
<li class="chapter" data-level="13.3.2" data-path="C-DataSystems.html"><a href="C-DataSystems.html#confirmatory-techniques"><i class="fa fa-check"></i><b>13.3.2</b> Confirmatory Techniques</a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="C-DataSystems.html"><a href="C-DataSystems.html#some-r-functions"><i class="fa fa-check"></i><b>13.4</b> Some R Functions</a></li>
<li class="chapter" data-level="13.5" data-path="C-DataSystems.html"><a href="C-DataSystems.html#summary"><i class="fa fa-check"></i><b>13.5</b> Summary</a></li>
<li class="chapter" data-level="13.6" data-path="C-DataSystems.html"><a href="C-DataSystems.html#DS:further-reading-and-resources"><i class="fa fa-check"></i><b>13.6</b> Further Resources and Contributors</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html"><i class="fa fa-check"></i><b>14</b> Dependence Modeling</a><ul>
<li class="chapter" data-level="14.1" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:VarTypes"><i class="fa fa-check"></i><b>14.1</b> Variable Types</a><ul>
<li class="chapter" data-level="14.1.1" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:QuaVar"><i class="fa fa-check"></i><b>14.1.1</b> Qualitative Variables</a></li>
<li class="chapter" data-level="14.1.2" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:QuanVar"><i class="fa fa-check"></i><b>14.1.2</b> Quantitative Variables</a></li>
<li class="chapter" data-level="14.1.3" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#multivariate-variables"><i class="fa fa-check"></i><b>14.1.3</b> Multivariate Variables</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:Measures"><i class="fa fa-check"></i><b>14.2</b> Classic Measures of Scalar Associations</a><ul>
<li class="chapter" data-level="14.2.1" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#association-measures-for-quantitative-variables"><i class="fa fa-check"></i><b>14.2.1</b> Association Measures for Quantitative Variables</a></li>
<li class="chapter" data-level="14.2.2" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#rank-based-measures"><i class="fa fa-check"></i><b>14.2.2</b> Rank Based Measures</a></li>
<li class="chapter" data-level="14.2.3" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#nominal-variables"><i class="fa fa-check"></i><b>14.2.3</b> Nominal Variables</a></li>
<li class="chapter" data-level="14.2.4" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#ordinal-variables"><i class="fa fa-check"></i><b>14.2.4</b> Ordinal Variables</a></li>
<li class="chapter" data-level="14.2.5" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#interval-variables"><i class="fa fa-check"></i><b>14.2.5</b> Interval Variables</a></li>
<li class="chapter" data-level="14.2.6" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#discrete-and-continuous-variables"><i class="fa fa-check"></i><b>14.2.6</b> Discrete and Continuous Variables</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:Copula"><i class="fa fa-check"></i><b>14.3</b> Introduction to Copulas</a></li>
<li class="chapter" data-level="14.4" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:CopAppl"><i class="fa fa-check"></i><b>14.4</b> Application Using Copulas</a><ul>
<li class="chapter" data-level="14.4.1" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#data-description"><i class="fa fa-check"></i><b>14.4.1</b> Data Description</a></li>
<li class="chapter" data-level="14.4.2" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#marginal-models"><i class="fa fa-check"></i><b>14.4.2</b> Marginal Models</a></li>
<li class="chapter" data-level="14.4.3" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#probability-integral-transformation"><i class="fa fa-check"></i><b>14.4.3</b> Probability Integral Transformation</a></li>
<li class="chapter" data-level="14.4.4" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#joint-modeling-with-copula-function"><i class="fa fa-check"></i><b>14.4.4</b> Joint Modeling with Copula Function</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:CopTyp"><i class="fa fa-check"></i><b>14.5</b> Types of Copulas</a><ul>
<li class="chapter" data-level="14.5.1" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#elliptical-copulas"><i class="fa fa-check"></i><b>14.5.1</b> Elliptical Copulas</a></li>
<li class="chapter" data-level="14.5.2" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#archimedian-copulas"><i class="fa fa-check"></i><b>14.5.2</b> Archimedian Copulas</a></li>
<li class="chapter" data-level="14.5.3" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#properties-of-copulas"><i class="fa fa-check"></i><b>14.5.3</b> Properties of Copulas</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#S:CopImp"><i class="fa fa-check"></i><b>14.6</b> Why is Dependence Modeling Important?</a></li>
<li class="chapter" data-level="14.7" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#Dep:further-reading-and-resources"><i class="fa fa-check"></i><b>14.7</b> Further Resources and Contributors</a><ul>
<li class="chapter" data-level="" data-path="C-DependenceModel.html"><a href="C-DependenceModel.html#ts-14.a.-other-classic-measures-of-scalar-associations"><i class="fa fa-check"></i>TS 14.A. Other Classic Measures of Scalar Associations</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="C-AppA.html"><a href="C-AppA.html"><i class="fa fa-check"></i><b>15</b> Appendix A: Review of Statistical Inference</a><ul>
<li class="chapter" data-level="15.1" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:BASIC"><i class="fa fa-check"></i><b>15.1</b> Basic Concepts</a><ul>
<li class="chapter" data-level="15.1.1" data-path="C-AppA.html"><a href="C-AppA.html#random-sampling"><i class="fa fa-check"></i><b>15.1.1</b> Random Sampling</a></li>
<li class="chapter" data-level="15.1.2" data-path="C-AppA.html"><a href="C-AppA.html#sampling-distribution"><i class="fa fa-check"></i><b>15.1.2</b> Sampling Distribution</a></li>
<li class="chapter" data-level="15.1.3" data-path="C-AppA.html"><a href="C-AppA.html#central-limit-theorem"><i class="fa fa-check"></i><b>15.1.3</b> Central Limit Theorem</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:PE"><i class="fa fa-check"></i><b>15.2</b> Point Estimation and Properties</a><ul>
<li class="chapter" data-level="15.2.1" data-path="C-AppA.html"><a href="C-AppA.html#method-of-moments-estimation"><i class="fa fa-check"></i><b>15.2.1</b> Method of Moments Estimation</a></li>
<li class="chapter" data-level="15.2.2" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:MLE"><i class="fa fa-check"></i><b>15.2.2</b> Maximum Likelihood Estimation</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:IE"><i class="fa fa-check"></i><b>15.3</b> Interval Estimation</a><ul>
<li class="chapter" data-level="15.3.1" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:IE:ED"><i class="fa fa-check"></i><b>15.3.1</b> Exact Distribution for Normal Sample Mean</a></li>
<li class="chapter" data-level="15.3.2" data-path="C-AppA.html"><a href="C-AppA.html#large-sample-properties-of-mle"><i class="fa fa-check"></i><b>15.3.2</b> Large-sample Properties of MLE</a></li>
<li class="chapter" data-level="15.3.3" data-path="C-AppA.html"><a href="C-AppA.html#confidence-interval"><i class="fa fa-check"></i><b>15.3.3</b> Confidence Interval</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:HT"><i class="fa fa-check"></i><b>15.4</b> Hypothesis Testing</a><ul>
<li class="chapter" data-level="15.4.1" data-path="C-AppA.html"><a href="C-AppA.html#basic-concepts"><i class="fa fa-check"></i><b>15.4.1</b> Basic Concepts</a></li>
<li class="chapter" data-level="15.4.2" data-path="C-AppA.html"><a href="C-AppA.html#student-t-test-based-on-mle"><i class="fa fa-check"></i><b>15.4.2</b> Student-<span class="math inline">\(t\)</span> test based on MLE</a></li>
<li class="chapter" data-level="15.4.3" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:HT:LRT"><i class="fa fa-check"></i><b>15.4.3</b> Likelihood Ratio Test</a></li>
<li class="chapter" data-level="15.4.4" data-path="C-AppA.html"><a href="C-AppA.html#S:AppA:HT:IC"><i class="fa fa-check"></i><b>15.4.4</b> Information Criteria</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="16" data-path="C-AppB.html"><a href="C-AppB.html"><i class="fa fa-check"></i><b>16</b> Appendix B: Iterated Expectations</a><ul>
<li class="chapter" data-level="16.1" data-path="C-AppB.html"><a href="C-AppB.html#S:AppB:CD"><i class="fa fa-check"></i><b>16.1</b> Conditional Distribution and Conditional Expectation</a><ul>
<li class="chapter" data-level="16.1.1" data-path="C-AppB.html"><a href="C-AppB.html#conditional-distribution"><i class="fa fa-check"></i><b>16.1.1</b> Conditional Distribution</a></li>
<li class="chapter" data-level="16.1.2" data-path="C-AppB.html"><a href="C-AppB.html#conditional-expectation-and-conditional-variance"><i class="fa fa-check"></i><b>16.1.2</b> Conditional Expectation and Conditional Variance</a></li>
</ul></li>
<li class="chapter" data-level="16.2" data-path="C-AppB.html"><a href="C-AppB.html#S:AppB:IE"><i class="fa fa-check"></i><b>16.2</b> Iterated Expectations and Total Variance</a><ul>
<li class="chapter" data-level="16.2.1" data-path="C-AppB.html"><a href="C-AppB.html#law-of-iterated-expectations"><i class="fa fa-check"></i><b>16.2.1</b> Law of Iterated Expectations</a></li>
<li class="chapter" data-level="16.2.2" data-path="C-AppB.html"><a href="C-AppB.html#law-of-total-variance"><i class="fa fa-check"></i><b>16.2.2</b> Law of Total Variance</a></li>
<li class="chapter" data-level="16.2.3" data-path="C-AppB.html"><a href="C-AppB.html#application"><i class="fa fa-check"></i><b>16.2.3</b> Application</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="C-AppB.html"><a href="C-AppB.html#S:AppConjugateDistributions"><i class="fa fa-check"></i><b>16.3</b> Conjugate Distributions</a><ul>
<li class="chapter" data-level="16.3.1" data-path="C-AppB.html"><a href="C-AppB.html#linear-exponential-family"><i class="fa fa-check"></i><b>16.3.1</b> Linear Exponential Family</a></li>
<li class="chapter" data-level="16.3.2" data-path="C-AppB.html"><a href="C-AppB.html#conjugate-distributions"><i class="fa fa-check"></i><b>16.3.2</b> Conjugate Distributions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="17" data-path="C-AppC.html"><a href="C-AppC.html"><i class="fa fa-check"></i><b>17</b> Appendix C: Maximum Likelihood Theory</a><ul>
<li class="chapter" data-level="17.1" data-path="C-AppC.html"><a href="C-AppC.html#S:AppC:LF"><i class="fa fa-check"></i><b>17.1</b> Likelihood Function</a><ul>
<li class="chapter" data-level="17.1.1" data-path="C-AppC.html"><a href="C-AppC.html#likelihood-and-log-likelihood-functions"><i class="fa fa-check"></i><b>17.1.1</b> Likelihood and Log-likelihood Functions</a></li>
<li class="chapter" data-level="17.1.2" data-path="C-AppC.html"><a href="C-AppC.html#properties-of-likelihood-functions"><i class="fa fa-check"></i><b>17.1.2</b> Properties of Likelihood Functions</a></li>
</ul></li>
<li class="chapter" data-level="17.2" data-path="C-AppC.html"><a href="C-AppC.html#S:AppC:MLE"><i class="fa fa-check"></i><b>17.2</b> Maximum Likelihood Estimators</a><ul>
<li class="chapter" data-level="17.2.1" data-path="C-AppC.html"><a href="C-AppC.html#definition-and-derivation-of-mle"><i class="fa fa-check"></i><b>17.2.1</b> Definition and Derivation of MLE</a></li>
<li class="chapter" data-level="17.2.2" data-path="C-AppC.html"><a href="C-AppC.html#asymptotic-properties-of-mle"><i class="fa fa-check"></i><b>17.2.2</b> Asymptotic Properties of MLE</a></li>
<li class="chapter" data-level="17.2.3" data-path="C-AppC.html"><a href="C-AppC.html#use-of-maximum-likelihood-estimation"><i class="fa fa-check"></i><b>17.2.3</b> Use of Maximum Likelihood Estimation</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="C-AppC.html"><a href="C-AppC.html#S:AppC:SI"><i class="fa fa-check"></i><b>17.3</b> Statistical Inference Based on Maximum Likelhood Estimation</a><ul>
<li class="chapter" data-level="17.3.1" data-path="C-AppC.html"><a href="C-AppC.html#hypothesis-testing"><i class="fa fa-check"></i><b>17.3.1</b> Hypothesis Testing</a></li>
<li class="chapter" data-level="17.3.2" data-path="C-AppC.html"><a href="C-AppC.html#S:AppC:MLEModelVal"><i class="fa fa-check"></i><b>17.3.2</b> MLE and Model Validation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="18" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html"><i class="fa fa-check"></i><b>18</b> Appendix D: Summary of Distributions</a><ul>
<li class="chapter" data-level="18.1" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#discrete-distributions"><i class="fa fa-check"></i><b>18.1</b> Discrete Distributions</a><ul>
<li class="chapter" data-level="18.1.1" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#the-ab0-class"><i class="fa fa-check"></i><b>18.1.1</b> The (a,b,0) Class</a></li>
<li class="chapter" data-level="18.1.2" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#the-ab1-class"><i class="fa fa-check"></i><b>18.1.2</b> The (a,b,1) Class</a></li>
</ul></li>
<li class="chapter" data-level="18.2" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#continuous-distributions"><i class="fa fa-check"></i><b>18.2</b> Continuous Distributions</a><ul>
<li class="chapter" data-level="18.2.1" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#one-parameter-distributions"><i class="fa fa-check"></i><b>18.2.1</b> One Parameter Distributions</a></li>
<li class="chapter" data-level="18.2.2" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#two-parameter-distributions"><i class="fa fa-check"></i><b>18.2.2</b> Two Parameter Distributions</a></li>
<li class="chapter" data-level="18.2.3" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#three-parameter-distributions"><i class="fa fa-check"></i><b>18.2.3</b> Three Parameter Distributions</a></li>
<li class="chapter" data-level="18.2.4" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#four-parameter-distribution"><i class="fa fa-check"></i><b>18.2.4</b> Four Parameter Distribution</a></li>
<li class="chapter" data-level="18.2.5" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#other-distributions"><i class="fa fa-check"></i><b>18.2.5</b> Other Distributions</a></li>
<li class="chapter" data-level="18.2.6" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#distributions-with-finite-support"><i class="fa fa-check"></i><b>18.2.6</b> Distributions with Finite Support</a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="C-SummaryDistributions.html"><a href="C-SummaryDistributions.html#limited-expected-values"><i class="fa fa-check"></i><b>18.3</b> Limited Expected Values</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="bibliography.html"><a href="bibliography.html"><i class="fa fa-check"></i>Bibliography</a></li>
<li class="divider"></li>
<li><a href="https://github.com/OpenActTexts/Loss-Data-Analytics" target="blank">Loss Data Analytics on GitHub</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Loss Data Analytics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="C:BonusMalus" class="section level1">
<h1><span class="header-section-number">Chapter 12</span> Experience Rating using Bonus-Malus</h1>
<hr />
<p><strong>This chapter is being written and is not yet complete nor edited. It is here to give you a flavor of what will be in the final version.</strong></p>
<hr />
<div id="S:ERBM:Intro" class="section level2">
<h2><span class="header-section-number">12.1</span> Introduction</h2>
<p><a href="#" class="tooltip" style="color:green"><em>Bonus-malus system</em><span style="font-size:8pt">A type of rating mechanism where insured premiums are adjusted based on their individual loss experience history</span></a>, which is used interchangeably as “no-fault discount”, “merit rating”, “experience rating” or “no-claim discount” in different countries, is based on penalizing insureds who are responsible for one or more claims by a premium surcharge, and awarding insureds with a premium discount if they do not have any claims. Insurers use bonus-malus systems for two main purposes; to encourage drivers to drive more carefully in a year without any claims, and to ensure insureds to pay premiums proportional to their risks based on their claims experience.</p>
<p><a href="#" class="tooltip" style="color:green"><em>No Claim Discount (NCD) system</em><span style="font-size:8pt">A type of experience rating where insureds obtain discounts on future years’ premiums based on claims-free experience</span></a> is an experience rating system commonly used in motor insurance. It represents an attempt to categorize insureds into homogeneous groups who pay premiums based on their claims experience. Depending on the rules in the scheme, new policyholders may be required to pay full premium initially, and obtain discounts in the future years as a results of claim-free years. An NCD system rewards policyholders for not making any claims during a year, or in other words, it grants a bonus to a careful driver. This bonus principle may affect policy holders’ decisions whether to claim or not to claim, especially when involving accidents with slight damages, which is known as ‘<a href="#" class="tooltip" style="color:green"><em>hunger for bonus</em><span style="font-size:8pt">Phenomenon where insureds under an experience rating system are dissuaded from filing minor claims in order to keep their no-claims discount</span></a>’ phenomenon. The option of ‘hunger for bonus’ under an NCD system may reduce insurers’ claim costs, and may be able to offset the expected decrease in premium income.</p>
</div>
<div id="S:ERBM:NCD" class="section level2">
<h2><span class="header-section-number">12.2</span> NCD System in Several Countries</h2>
<div id="ncd-system-in-malaysia" class="section level3">
<h3><span class="header-section-number">12.2.1</span> NCD System in Malaysia</h3>
<p>Before the liberalization of Motor Tariff on 1st July 2017, the rating of motor insurance in Malaysia was governed by Motor Tariff. Under the tariff, the rate charged should not be lower than the rates specified under the classes of risks, to ensure that the price competition among insurers will not go below the country’s economic level. The basic rating factors considered were scope of insurance, cubic capacity of vehicle and estimated value of vehicle (or sum insured, whichever is lower). Under the Motor Tariff, the final premium to be paid is adjusted by the policyholder’s claim experience, or equivalently, his NCD entitlement.</p>
<p>Effective on 1st July 2017, the premium rates for motor insurance are liberalized, or de-tariffed. The pricing of premium is now determined by individual insurers and <a href="#" class="tooltip" style="color:green"><em>takaful</em><span style="font-size:8pt">Co-operative system of reimbursement or repayment in case of loss as an insurance alternative</span></a> operators, and the consumers are able to enjoy a wider choice of motor insurance products at competitive prices. Since tariff liberalization encourages innovation and competition among insurers and takaful operators, the premiums are based on broader risk factors other than the two rating factors specified in the Motor Tariff, i.e. sum insured and cubic capacity of vehicle. Other rating factors may be defined in the risk profile of an insured, such as age of vehicle, age of driver, safety and security features of vehicle, geographical location of vehicle and traffic offences of driver. As different insurers and takaful operators have different ways of defining the risk profile of an insured, the price of a policy may differ from one insurer to another. However, the NCD structure from the Motor Tariff remains ‘unchanged’ and continue to exist, and is ‘transferable’ from one insurer, or from one takaful operator, to another.</p>
<p>The discounts in the Malaysian NCD system are divided into six classes, starting from the initial class of 0% discount, followed by classes of 25%, 30%, 38.3%, 45% and 55% discounts. Table 1 provides the classes of NCD system in Malaysia. A claim-free year indicates that a policyholder is entitled to move one-step forward to the next discount class, such as from a 0% discount to a 25% discount in the renewal year. If a policyholder is already at the highest class, which is at a 55% discount, a claim-free year indicates that the policyholder remains in the same class. On the other hand, if one or more claims are made within the year, the NCD will be forfeited and the policyholder has to start at 0% discount in the renewal year. In other words, the policyholder has to pay a full premium for the next year’s renewal premium, regardless of his current class of NCD.</p>
<p>For an illustration purpose, Figure <a href="C-BonusMalus.html#fig:TransitionMsia">12.1</a> shows the transition diagram for the NCD classes under the Malaysian Motor Tariff. The transition starts at class 0, and increase one by one if an insured has a no-claim year. If an insured has one or more claims within the year, the current class automatically returns to class 0.</p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 1: Classes of NCD (Malaysia)}\\
\begin{array}{*{20}c}
\hline
\text{Classes (claim-free years)} &amp; \text{Discounts}\\
\hline\\
{0} &amp; {0}\\
{1} &amp; {25}\\
{2} &amp; {30}\\
{3} &amp; {38.33}\\
{4} &amp; {45}\\
{5\text{ and above}} &amp; {55}\\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:TransitionMsia"></span>
<img src="Figures/FigureTransitionMsia.png" alt="Transition diagram for NCD classes (Malaysia)" width="80%" />
<p class="caption">
Figure 12.1: Transition diagram for NCD classes (Malaysia)
</p>
</div>
</div>
<div id="ncd-system-in-other-countries" class="section level3">
<h3><span class="header-section-number">12.2.2</span> NCD System in Other Countries</h3>
<p>The NCD system in Brazil are subdivided into seven classes, with the following premium levels (Lemaire 1998): 100, 90, 85, 80, 75, 70, and 65. These premium levels are also equivalent to the following discount classes: 0%, 10%, 15%, 20%, 25%, 30% and 45%. New policyholders have to start at 0% discount, or at level 100, and a claim-free year indicates that a policyholder can move forward at a one-class discount. If one or more claims incurred within the year, the policyholder has to move backward, also at a one-class discount. Table 2 and Figure <a href="C-BonusMalus.html#fig:TransitionBrazil">12.2</a> respectively show the classes and the transition diagram for the NCD system in Brazil.</p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 2: Classes of NCD (Brazil)}\\
\begin{array}{*{20}c}
\hline
\text{Classes (claim-free years)} &amp; \text{Discounts}\\
\hline\\
{0} &amp; {0}\\
{1} &amp; {10}\\
{2} &amp; {15}\\
{3} &amp; {20}\\
{4} &amp; {25}\\
{5} &amp; {30}\\
{6\text{ and above}} &amp; {45}\\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:TransitionBrazil"></span>
<img src="Figures/FigureTransitionBrazil.png" alt="Transition diagram for NCD classes (Brazil)" width="80%" />
<p class="caption">
Figure 12.2: Transition diagram for NCD classes (Brazil)
</p>
</div>
<p>The NCD system in Switzerland, which is implemented in 1990, are subdivided into twenty-two classes, with the following premium levels: 270, 250, 230, 215, 200, 185, 170, 155, 140, 130, 120, 110, 100, 90, 80, 75, 70, 65, 60, 55, 50 and 45 (Lemaire and Zi 1994). These levels are also equivalent to the following loadings: 170%, 150%, 130%, 115%, 100%, 85%, 70%, 55%, 40%, 30%, 20%, and 10%, and the following discounts: 0%, 10%, 20%, 25%, 30%, 35%, 40%, 45%, 50% and 55%. New policyholders have to start at 170% loading, or at 270 premium level, and a claim-free year indicates that a policyholder can move one-class forward. If one or more claims incurred within the year, the policyholder has to move four-classes backwards. Table 3 and Figure <a href="C-BonusMalus.html#fig:TransitionSwitz">12.3</a> respectively show the classes and the transition diagram for the NCD system in Switzerland.</p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 3: Classes of NCD (Switzerland)}\\
\begin{array}{*{20}c}
\hline
\text{Classes} &amp; \text{Loadings} &amp; \text{Classes} &amp; \text{Discounts}\\
\text{(claim-free years)} &amp; &amp; \text{(claim-free years)} &amp; \\
\hline\\
{0} &amp; {170} &amp; {12} &amp; {0}\\
{1} &amp; {150} &amp; {13} &amp; {10}\\
{2} &amp; {130} &amp; {14} &amp; {20}\\
{3} &amp; {115} &amp; {15} &amp; {25}\\
{4} &amp; {100} &amp; {16} &amp; {30}\\
{5} &amp; {85} &amp; {17} &amp; {35}\\
{6} &amp; {70} &amp; {18} &amp; {40}\\
{7} &amp; {55} &amp; {19} &amp; {45}\\
{8} &amp; {40} &amp; {20} &amp; {50}\\
{9} &amp; {30} &amp; {21 \text{ and above}} &amp; {55}\\
{10} &amp; {20} &amp;&amp; \\
{11} &amp; {10} &amp;&amp; \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:TransitionSwitz"></span>
<img src="Figures/FigureTransitionSwitz.png" alt="Transition diagram for NCD classes (Switzerland)" width="80%" />
<p class="caption">
Figure 12.3: Transition diagram for NCD classes (Switzerland)
</p>
</div>
</div>
</div>
<div id="S:ERBM:BMS" class="section level2">
<h2><span class="header-section-number">12.3</span> BMS and Markov Chain Model</h2>
<p>A BMS, or an NCD system, can be represented by a discrete time parameter <a href="#" class="tooltip" style="color:green"><em>Markov chain</em><span style="font-size:8pt">A stochastic model (time dependent) where the probability of each event depends only on the current state and not the historical path</span></a>. Under this model, the state space consists of classes of bonus-malus, and the state (or class) is assumed to shift randomly from year to year. Therefore, it is important to know a brief description on two elements; a stochastic process that has a Markov property, and a discrete time Markov chain.</p>
<p><strong>Definition:</strong> A <strong><em>stochastic process</em></strong> has a Markov property if the <a href="https://en.wikipedia.org/wiki/Conditional_probability_distribution">probability distribution</a> of future states, conditional on both past and present states, depends only upon the present state and not on the sequence of events that preceded it.</p>
<p><strong>Definition:</strong> A <strong><em>discrete time Markov chain</em></strong> is a stochastic process that can be parameterized by empirically estimating the transition probabilities between discrete states.</p>
<div id="transition-probability" class="section level3">
<h3><span class="header-section-number">12.3.1</span> Transition Probability</h3>
<p>The randomness of the transition of the NCD classes is governed by the transition probability in a given year. The definition of a transition probability is provided here to understand the use of the probability for representing the transition of the NCD classes.</p>
<p><strong>Definition:</strong> The <strong><em>transition probability</em></strong> from state <span class="math inline">\(i\)</span> (at time <span class="math inline">\(n\)</span>) to state <span class="math inline">\(j\)</span> (at time <span class="math inline">\(n + 1\)</span>) is called a one-step transition probability, and is denoted by <span class="math inline">\(p_{ij} = Pr (X_{n + 1} = j|X_n = i)\)</span>, <span class="math inline">\(i = 1,2,...,k\)</span>, <span class="math inline">\(j = 1,2,...,k\)</span>.</p>
<p>The transition probabilities can be represented by a <span class="math inline">\(k \times k\)</span> matrix. Assuming a homogeneous Markov process, a <em>k</em>-state Markov chain can be represented by a <strong><em>matrix of transition probabilities</em></strong> <span class="math inline">\({\bf P}\)</span>:</p>
<p><span class="math display">\[
{\bf P} = 
\left[ {\begin{array}{*{20}c}
p_{11} &amp; p_{12} &amp; \ldots &amp; &amp; &amp; p_{1k} \\
p_{21} &amp; p_{22} &amp; \ldots &amp; &amp; &amp; p_{2k} \\ 
\vdots &amp; \ddots &amp; &amp; &amp; &amp; \vdots \\
 &amp; &amp; &amp; &amp; &amp; \\
 &amp; &amp; &amp; &amp; &amp; \\
p_{k1} &amp; p_{k2} &amp; \cdots &amp; &amp; &amp; p_{kk}   
\end{array} } \right].
\]</span></p>
<p>Each row of the <a href="#" class="tooltip" style="color:green"><em>transition matrix</em><span style="font-size:8pt">Matrix that represents all probabilities for transition from one state to another (could be same state) for a markov chain</span></a> represents the transition of flowing out of state, whereas each column represents the transition of flowing into the state. The cumulative transitions of flowing out of state must equal 1, or each row of the matrix must sum to 1, i.e. <span class="math inline">\(\sum\limits_j p_{ij} = 1\)</span>. All probabilities must also be non-negative (since they are probabilities), i.e. <span class="math inline">\(p_{ij} \ge 0\)</span>.</p>
<p>Consider the Malaysian NCD system. Under this system, let the random variable <span class="math inline">\(X_t\)</span> denotes the class of NCD at time <span class="math inline">\(t\)</span> and takes the values in a state space <span class="math inline">\(\bf{S}\)</span>, where <span class="math inline">\({\bf S} = \{0,1,...,5\}\)</span>. Therefore, the probability of a no-claim year is equal to the probability of transition from state <span class="math inline">\(i\)</span> to state <span class="math inline">\(j\)</span>, which is <span class="math inline">\(p_{ij}\)</span>, <span class="math inline">\(i = 0,1,2,...,5\)</span>, <span class="math inline">\(j = 0,1,2,...,5\)</span>. If an insured has one or more claims within the year, the probability of transitioning back to state 0 is represented by <span class="math inline">\(p_{i0}\)</span>, which is also equivalent to <span class="math inline">\(1 - {p_{ij}}.\)</span> Therefore, there are only two transition probabilities in each row; the probability of advancing to the next state, <span class="math inline">\(p_{ij},\)</span> and the probability of returning back to state zero, <span class="math inline">\(p_{i0} = 1 - p_{ij}\)</span>.</p>
<p>In terms of transition probabilities, the Malaysian NCD system can be represented by the following <span class="math inline">\((6 \times 6)\)</span> transition matrix:</p>
<p><span class="math display">\[
{\bf P} = 
\left[ {\begin{array}{*{20}c}
p_{00}&amp;p_{01}&amp;0&amp;0&amp;0&amp;0\\
p_{10}&amp;0&amp;p_{12}&amp;0&amp;0&amp;0\\
p_{20}&amp;0&amp;0&amp;p_{23}&amp;0&amp;0\\
p_{30}&amp;0&amp;0&amp;0&amp;p_{34}&amp;0\\
p_{40}&amp;0&amp;0&amp;0&amp;0&amp;p_{45}\\
p_{50}&amp;0&amp;0&amp;0&amp;0&amp;p_{55}
\end{array} }\right] = 
\left[ {\begin{array}{*{20}c}
{1 - p_{01}}&amp;p_{01}&amp;0&amp;0&amp;0&amp;0\\
{1 - p_{12}}&amp;0&amp;p_{12}&amp;0&amp;0&amp;0\\
{1 - p_{23}}&amp;0&amp;0&amp;p_{23}&amp;0&amp;0\\
{1 - p_{34}}&amp;0&amp;0&amp;0&amp;p_{34}&amp;0\\
{1 - p_{45}}&amp;0&amp;0&amp;0&amp;0&amp;p_{45}\\
{1 - p_{55}}&amp;0&amp;0&amp;0&amp;0&amp;p_{55}
\end{array} }\right]
\]</span></p>
<p><strong><em>Example 1</em></strong></p>
<p><em>Provide the transition matrix for the NCD system in Brazil.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>Based on the NCD classes and the transition diagram shown respectively in Table 2 and Figure <a href="C-BonusMalus.html#fig:TransitionBrazil">12.2</a>, the probability of a no-claim year is equal to the probability of moving one-class forward, whereas the probability of having one or more claims within the year is equal to the probability of moving one-class backward. Therefore, each row can contain two or more transition probabilities; one probability for advancing to the next state, and one or more probabilities for moving one-class backwards. The transition matrix is:</em></p>
<p><span class="math display">\[
{\bf P} = 
\left[ {\begin{array}{*{20}{c}}
{1 - p_{01}}&amp;p_{01}&amp;0&amp;0&amp;0&amp;0&amp;0\\
{1 - p_{12}}&amp;0&amp;p_{12}&amp;0&amp;0&amp;0&amp;0\\
{1 - \sum\limits_j p_{2j}}&amp;p_{21}&amp;0&amp;p_{23}&amp;0&amp;0&amp;0\\
{1 - \sum\limits_j p_{3j}}&amp;p_{31}&amp;p_{32}&amp;0&amp;p_{34}&amp;0&amp;0\\\
{1 - \sum\limits_j p_{4j}}&amp;p_{41}&amp;p_{42}&amp;p_{43}&amp;0&amp;p_{45}&amp;0\\
{1 - \sum\limits_j p_{5j}}&amp;p_{51}&amp;p_{52}&amp;p_{53}&amp;p_{54}&amp;0&amp;p_{56}\\
{1 - \sum\limits_j p_{6j}}&amp;p_{61}&amp;p_{62}&amp;p_{63}&amp;p_{64}&amp;p_{65}&amp;p_{66}
\end{array} } \right]
\]</span></p>
<p><strong><em>Example 2</em></strong></p>
<p><em>Provide the transition matrix for the NCD system in Switzerland.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>From Table 3 and Figure</em> <a href="C-BonusMalus.html#fig:TransitionSwitz">12.3</a><em>, the probability of a no-claim year is equal to the probability of moving one-class forward, whereas the probability of having one or more claims within the year is equal to the probability of moving four-classes backward. The transition matrix is:</em></p>
<p><span class="math display">\[
\begin{matrix}
\left|
{\begin{array}{*{12}{c}}
1 - {p_{01}} &amp; p_{01} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - {p_{12}} &amp; 0 &amp; p_{12} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - {p_{23}} &amp; 0 &amp; 0 &amp; p_{23} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - {p_{34}} &amp; 0 &amp; 0 &amp; 0 &amp; p_{34} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - {p_{45}} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; p_{45} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - \sum\limits_j {p_{5j}} &amp; p_{51} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; p_{56} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - \sum\limits_j {p_{6j}} &amp; 0 &amp; p_{62} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; p_{67} &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - \sum\limits_j {p_{7j}} &amp; 0 &amp; 0 &amp; p_{73} &amp; 0 &amp; 0 &amp; 0 &amp; 0 &amp; p_{78} &amp; 0 &amp; 0 &amp; \cdots\\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; \ddots\\
1 - \sum\limits_j {p_{19,j}} &amp; 0 &amp; 0 &amp; p_{19,3} &amp; 0 &amp; 0 &amp; 0 &amp; p_{19,7} &amp; 0 &amp; 0 &amp; 0 &amp; \cdots\\
1 - \sum\limits_j {p_{20,j}} &amp; 0 &amp; 0 &amp; 0 &amp; p_{20,4} &amp; 0 &amp; 0 &amp; 0 &amp; p_{20,8} &amp; 0 &amp; 0 &amp; \cdots\\
1 - \sum\limits_j {p_{21,j}} &amp; p_{21,1} &amp; 0 &amp; 0 &amp; 0 &amp; p_{21,5} &amp; 0 &amp; 0 &amp; 0 &amp; p_{21,9} &amp; 0 &amp; \cdots
\end{array}} \right|
\end{matrix}
\]</span></p>
</div>
</div>
<div id="S:ERBM:StatDist" class="section level2">
<h2><span class="header-section-number">12.4</span> BMS and Stationary Distribution</h2>
<div id="stationary-distribution" class="section level3">
<h3><span class="header-section-number">12.4.1</span> Stationary Distribution</h3>
<p>It is important to note that the transition matrix represents the transition probabilities of the NCD classes in one year. If we are interested in the distribution of the transition in the long run (which may take several years), the stationary probability can be used.</p>
<p>Several definitions and properties are provided here to understand the use of a Markov chain model for representing the stationary distribution of the NCD transitions. However, students are encouraged to refer to textbooks on Markov Chain and stochastic processes available in the literature for a more comprehensive knowledge on the related subjects.</p>
<p><strong>Definition:</strong> A Markov chain is said to be <strong><em>irreducible</em></strong> if it is possible to move to any state from any other state.</p>
<p><strong>Definition:</strong> A state <span class="math inline">\(i\)</span> has <strong>period</strong> <span class="math inline">\(k\)</span> if any return to state <span class="math inline">\(i\)</span> must occur in multiples of <span class="math inline">\(k\)</span> time steps. If <span class="math inline">\(k = 1\)</span>, then the state is said to be <strong><em>aperiodic</em></strong>.</p>
<p><strong>Definition:</strong> A state <span class="math inline">\(i\)</span> is said to be <strong>transient</strong> if, given that we start in state <span class="math inline">\(i\)</span>, there is a non-zero probability that we will never return to <span class="math inline">\(i\)</span>. State <span class="math inline">\(i\)</span> is recurrent (or persistent) if it is not transient. A state <span class="math inline">\(i\)</span> is <strong><em>positive recurrent</em></strong> if the <strong>mean recurrent time</strong> (or expected return time) is <strong><em>finite</em></strong>.</p>
<p><strong>Definition:</strong> A state <span class="math inline">\(i\)</span> is said to be <em><a href="https://en.wikipedia.org/wiki/Ergodic_theory"><strong>ergodic</strong></a></em> if it is aperiodic and positive recurrent. In other words, a state <span class="math inline">\(i\)</span> is ergodic if it is recurrent, has a period of one (aperiodic), and has finite mean recurrence time. If all states in an irreducible Markov chain are ergodic, then the chain is said to be ergodic.</p>
<p><strong>Definition:</strong> Let <span class="math inline">\(p_{ij}^{(n)} = \Pr ({X_n} = j\|{X_0} = i)\)</span> be the probability of transition from state <span class="math inline">\(i\)</span> to state <span class="math inline">\(j\)</span> in <span class="math inline">\(n\)</span> time steps. The <em>n</em>-step transition probabilities for a <strong><em>stationary Markov chain</em></strong> satisfy the <em><a href="https://en.wikipedia.org/wiki/Chapman%E2%80%93Kolmogorov_equation"><strong>Chapman–Kolmogorov equation</strong></a>:</em></p>
<p><span class="math display">\[p_{ij}^{(n)} = \sum\limits_r {p_{ir}^{(k)}p_{rj}^{(n - k)}}\]</span></p>
<p>for any <span class="math inline">\(k\)</span>, where <span class="math inline">\(0 &lt; k &lt; n\)</span>.</p>
<p><strong>Definition:</strong> If a Markov chain is <em><a href="https://en.wikipedia.org/w/index.php?title=Time-homogeneous_Markov_chain&amp;action=edit&amp;redlink=1">stationary</a></em>, then the vector <span class="math inline">\({\bf{\pi }}\)</span> is called a <a href="#" class="tooltip" style="color:green"><em>stationary distribution</em><span style="font-size:8pt">Probability distribution remains unchanged in the markov chain as time progresses</span></a> (or <em><a href="https://en.wikipedia.org/wiki/Invariant_measure">invariant measure</a></em>) if it satisfies:</p>
<p><span class="math display">\[0 \le {\pi _j} \le 1\]</span></p>
<p><span class="math display">\[\sum\limits_j {{\pi _j}} = 1,\]</span></p>
<p><span class="math display">\[{\pi_j} = \sum\limits_i {\pi_i}p_{ij}\]</span>.</p>
<p>In terms of vectors and matrices, a stationary distribution <span class="math inline">\({\bf{\pi }}\)</span> is a row vector, whose entries are non-negative and sum to one, that is unchanged by the operation:</p>
<p><span class="math inline">\({\bf{\pi P}} = {\bf{\pi }}\)</span>.</p>
<p>If a Markov chain is stationary, then the transition matrix <span class="math inline">\({\bf{P}}\)</span> is the same after each step, so that the <span class="math inline">\(k\)</span>-step transition probability can be computed as the <span class="math inline">\(k\)</span>-th power of the transition matrix, <span class="math inline">\({{\bf{P}}^k}.\)</span></p>
<p>From the definitions and properties above, a BMS forms a regular Markov chain if all of its states (NCD classes) are <a href="#" class="tooltip" style="color:green"><em>ergodic</em><span style="font-size:8pt">Irreducible markov chain where it is eventually possible to move from any state to any other state, with positive probability</span></a>, and the chain is not cyclic (or <a href="#" class="tooltip" style="color:green"><em>irreversible</em><span style="font-size:8pt">A markov chain where there does not exist a probability distribution that allows for the chain to be walked backwards in time</span></a>). The row vector, <span class="math inline">\({\bf{\pi }}\)</span>, which is also the <strong><em>left</em></strong> <a href="#" class="tooltip" style="color:green"><em>eigenvector</em><span style="font-size:8pt">A non-zero vector that changes by only a scalar factor when that linear transformation is applied</span></a> of the transition matrix, is a <strong><em>stationary distribution</em></strong> defined by <span class="math inline">\(0 \le {\pi _j} \le 1\)</span> and <span class="math inline">\(\sum\limits_j {{\pi_j}} = 1\)</span>.</p>
<p><strong><em>Example 3</em></strong></p>
<p><em>Find the stationary distribution for the NCD system in Malaysia assuming that the probability of a no-claim year for all NCD classes are <span class="math inline">\({p_0}\)</span>.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>The transition matrix can be re-written as:</em></p>
<p><em>The stationary distribution can be calculated using</em> <span class="math inline">\({\pi _j} = \sum\limits_i {\pi _i}p_{ij}\)</span><em>. The solutions are:</em></p>
<p><span class="math display">\[
\begin{array}{l}
{\pi _0} = \sum\limits_i {\pi_i}p_{i0} = (1 - {p_0})\sum\limits_i {{\pi _i}} = 1 - {p_0}\\\\
{\pi _1} = \sum\limits_i {\pi _i}p_{i1} = {\pi_0}{p_{01}} = (1 - {p_0}){p_0}\\\\
{\pi _2} = \sum\limits_i {\pi _i}p_{i2} = {\pi _1}{p_{12}} = (1 - {p_0}){p_0}^2\\\\
{\pi _3} = \sum\limits_i {\pi _i}p_{i3} = {\pi _2}{p_{23}} = (1 - {p_0}){p_0}^3\\\\
{\pi _4} = \sum\limits_i {\pi _i}p_{i4} = {\pi _3}{p_{34}} = (1 - {p_0}){p_0}^4\\\\
{\pi _5} = \sum\limits_i {\pi _i}p_{i5} = {\pi _4}{p_{45}} + {\pi _5}{p_{55}} = (1 - {p_0}){p_0}^5 + {\pi _5}{p_0}\\\\
\therefore {\pi _5} = \frac{(1 - {p_0}){p_0}^5}{{(1 - {p_0})}} = {p_0}^5
\end{array}
\]</span></p>
<p>The stationary distribution (or steady state condition) shown in Example 3 represents the asymptotic distribution of the NCD system, or the distribution in the long run. As an example, assuming that the probability of a no-claim year is <span class="math inline">\(p_0 = 0.90,\)</span> the <strong><em>stationary probabilities</em></strong> are:</p>
<p><span class="math display">\[
\begin{array}{l}
{\pi _0} = 1 - {p_0} = 0.1000\\\\
{\pi _1} = (1 - {p_0}){p_0} = 0.0900\\\\
{\pi _2} = (1 - {p_0}){p_0}^2 = 0.0810\\\\
{\pi _3} = (1 - {p_0}){p_0}^3 = 0.0729\\\\
{\pi _4} = (1 - {p_0}){p_0}^4 = 0.0656\\\\
{\pi _5} = {p_0}^5 = 0.5905
\end{array}
\]</span></p>
<p>In other words, <span class="math inline">\({\pi_0} = 0.10\)</span> indicates that 10% of insureds will eventually belong to class 0 (or zero claim-free years), <span class="math inline">\({\pi _1} = 0.09\)</span> indicates that 9% of insureds will eventually belong to class 1 (or one claim-free year), and so forth, until <span class="math inline">\({\pi _5} = 0.59\)</span>, which indicates that 59% of insureds will eventually belong to class 5 (or five successive claim-free years).</p>
</div>
<div id="r-program-for-stationary-distribution" class="section level3">
<h3><span class="header-section-number">12.4.2</span> R Program for Stationary Distribution</h3>
<p>We can use the left eigenvector of a transition matrix to calculate the stationary distribution. The following R program can be used to calculate the left eigenvector:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#create transition matrix</span>
entries=<span class="kw">c</span>(<span class="fl">0.1</span>,<span class="fl">0.9</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dv">0</span>,<span class="fl">0.9</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9</span>)
TP=<span class="kw">matrix</span>(entries,<span class="dt">nrow=</span><span class="dv">6</span>,<span class="dt">byrow=</span><span class="ot">TRUE</span>)
TP</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4] [,5] [,6]
## [1,]  0.1  0.9  0.0  0.0  0.0  0.0
## [2,]  0.1  0.0  0.9  0.0  0.0  0.0
## [3,]  0.1  0.0  0.0  0.9  0.0  0.0
## [4,]  0.1  0.0  0.0  0.0  0.9  0.0
## [5,]  0.1  0.0  0.0  0.0  0.0  0.9
## [6,]  0.1  0.0  0.0  0.0  0.0  0.9</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#calculate left eigenvector</span>
<span class="co">#hint -- left eigenvector is the same as right eigenvector of transpose of transition matrix</span>
<span class="kw">eigen</span>(<span class="kw">t</span>(TP))</code></pre></div>
<pre><code>## eigen() decomposition
## $values
## [1]  1.0000000000+0.0000000000i -0.0004880382+0.0003546725i
## [3] -0.0004880382-0.0003546725i  0.0001865015+0.0005736028i
## [5]  0.0001865015-0.0005736028i  0.0006030733+0.0000000000i
## 
## $vectors
##              [,1]                                        [,2]
## [1,] 0.1615936+0i  0.00000000000011546+0.0000000000000838874i
## [2,] 0.1454342+0i -0.00000000006591101-0.0000000002025976972i
## [3,] 0.1308908+0i -0.00000009813867774+0.0000003022936262135i
## [4,] 0.1178017+0i  0.00038354290934278-0.0002787325538732070i
## [5,] 0.1060216+0i -0.70729837066103896+0.0000000000000000000i
## [6,] 0.9541940+0i  0.70691492595616912+0.0002784304627608034i
##                                             [,3]
## [1,]  0.00000000000011546-0.0000000000000838874i
## [2,] -0.00000000006591101+0.0000000002025976972i
## [3,] -0.00000009813867774-0.0000003022936262135i
## [4,]  0.00038354290934278+0.0002787325538732070i
## [5,] -0.70729837066103896+0.0000000000000000000i
## [6,]  0.70691492595616912-0.0002784304627608034i
##                                               [,4]
## [1,] -0.0000000000000440003+0.0000000000001357099i
## [2,]  0.0000000001723292683+0.0000000001248792837i
## [3,]  0.0000002567150759536-0.0000001869214542640i
## [4,] -0.0001468014877601952-0.0004505247500856750i
## [5,] -0.7070333538878578183+0.0004507115465249567i
## [6,]  0.7071798984882565753+0.0000000000000000000i
##                                               [,5]
## [1,] -0.0000000000000440003-0.0000000000001357099i
## [2,]  0.0000000001723292683-0.0000000001248792837i
## [3,]  0.0000002567150759536+0.0000001869214542640i
## [4,] -0.0001468014877601952+0.0004505247500856750i
## [5,] -0.7070333538878578183-0.0004507115465249567i
## [6,]  0.7071798984882565753+0.0000000000000000000i
##                           [,6]
## [1,]  0.0000000000001426323+0i
## [2,]  0.0000000002126778891+0i
## [3,]  0.0000003173909504803+0i
## [4,]  0.0004736602551468477+0i
## [5,]  0.7068696732221422252+0i
## [6,] -0.7073436510810596767+0i</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#divide entry of first column by sum of elements, so that entries sum to 1</span>
<span class="co">#provide answers in 4 decimal places</span>
<span class="kw">round</span>(<span class="kw">eigen</span>(<span class="kw">t</span>(TP))<span class="op">$</span>vectors[,<span class="dv">1</span>]<span class="op">/</span><span class="kw">sum</span>(<span class="kw">eigen</span>(<span class="kw">t</span>(TP))<span class="op">$</span>vectors[,<span class="dv">1</span>]),<span class="dv">4</span>)</code></pre></div>
<pre><code>## [1] 0.1000+0i 0.0900+0i 0.0810+0i 0.0729+0i 0.0656+0i 0.5905+0i</code></pre>
<p><strong><em>Example 4</em></strong></p>
<p><em>Find the stationary distribution for the NCD system in Brazil assuming that the number of successive years of claims is Poisson distributed with parameter</em> <span class="math inline">\(\lambda = 0.10\)</span>.</p>
<p><strong><em>Solution</em></strong></p>
<p><em>Under the Poisson distribution, the probability of</em> <span class="math inline">\(k\)</span> <em>successive years of claims is</em> <span class="math inline">\(p_k = \frac{e^{ - 0.1}{(0.1)}^k}{{k!}},{\rm{ }}k = 0,1,2,.....\)</span></p>
<p><em>The transition matrix is:</em></p>
<p><span class="math display">\[
{\small {\bf{P}} = \left[ {\begin{array}{*{20}{c}}
{1 - {p_0}}&amp;{{p_0}}&amp;0&amp;0&amp;0&amp;0&amp;0\\\\
{1 - {p_0}}&amp;0&amp;{{p_0}}&amp;0&amp;0&amp;0&amp;0\\\\
{1 -\sum\limits_i {{p_i}} }&amp;{{p_1}}&amp;0&amp;{{p_0}}&amp;0&amp;0&amp;0\\\\
{1 -\sum\limits_i {{p_i}} }&amp;{{p_2}}&amp;{{p_1}}&amp;0&amp;{{p_0}}&amp;0&amp;0\\\\
{1 - \sum\limits_i {{p_i}}}&amp;{{p_3}}&amp;{{p_2}}&amp;{{p_1}}&amp;0&amp;{{p_0}}&amp;0\\\\
{1 - \sum\limits_i{{p_i}} }&amp;{{p_4}}&amp;{{p_3}}&amp;{{p_2}}&amp;{{p_1}}&amp;0&amp;{{p_0}}\\\\
{1 - \sum\limits_i {{p_i}}}&amp;{{p_5}}&amp;{{p_4}}&amp;{{p_3}}&amp;{{p_2}}&amp;{{p_1}}&amp;{{p_0}}
\end{array}} \right] = 
\left[ {\begin{array}{*{20}{c}}
{0.0952}&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0\\\\
{0.0047}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0\\\\
{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0&amp;0\\\\
{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0\\\\
{0.0000}&amp;{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}\\\\
{0.0000}&amp;{0.0000}&amp;{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;{0.9048}
\end{array}}\right]}
\]</span></p>
<p><em>Using R program, the stationary probabilities are:</em></p>
<p><span class="math display">\[
\left[ {\begin{array}{*{20}{c}}
{{\pi _0}}\\\\
{{\pi_1}}\\\\
{{\pi _2}}\\\\
{{\pi _3}}\\\\
{{\pi _4}}\\\\
{{\pi_5}}\\\\
{{\pi _6}}
\end{array}} \right] = 
\left[ {\begin{array}{*{20}{c}}
{0.0000}\\\\
{0.0000}\\\\
{0.0003}\\\\
{0.0022}\\\\
{0.0145}\\\\
{0.0936}\\\\
{0.8894}
\end{array}} \right]
\]</span></p>
<p><em>The probabilities indicate that 89% of insureds will eventually belong to class 6 (six successive claim-free years), 9% of insureds will eventually belong to class 5 (five successive claim-free years), and 1.5% of insureds will eventually belong to class 4 (four successive claim-free years). Other classes, after combined, have less than 1% of insureds.</em></p>
<p><strong><em>Example 5</em></strong></p>
<p><em>Using the results from Example 4, find the final premium under the steady state condition assuming that the premium prior to implementing the NCD is</em> <span class="math inline">\(m.\)</span></p>
<p><strong><em>Solution</em></strong></p>
<p><em>Using the stationary probabilities from Example 4, the stationary final premium is:</em></p>
<p><span class="math display">\[
\begin{array}{l} = 
\sum\limits_j \text{(premium)} \times 
\text{(proportion in class } j \text{ in the long run)} \times \text{(1 - NCD in class } j)\\\\ 
= m[{\pi _0}(1) + {\pi _1}(1 - 0.9) + {\pi _2}(1 - 0.15) + \ldots + {\pi _6}(1 - 0.35)]\\\\ 
= m[0 + 0 + (0.0003)(0.85) + \ldots + (0.8894)(0.65)]\\\\
= 0.6565m
\end{array}
\]</span></p>
<p><em>The results indicate that the final premium reduce from m to 0.6565m in the long run (under steady state condition or stationary condition) if the NCD is considered.</em></p>
</div>
<div id="premium-evolution" class="section level3">
<h3><span class="header-section-number">12.4.3</span> Premium Evolution</h3>
<p>Sometimes we are interested to observe the evolution of the mean premium after <span class="math inline">\(n\)</span> years (or <span class="math inline">\(n\)</span> steps). Under the NCD system, the <a href="#" class="tooltip" style="color:green"><em>n-step transition probability</em><span style="font-size:8pt">Probability of ending in a state j after n periods, starting in state i, where i and j can be the same state</span></a>, <span class="math inline">\(p_{ij}^{(n)}\)</span>, can be used to observe the evolution of the mean premium. A definition on <em>n</em>-step transition probabaility <span class="math inline">\(p_{ij}^{(n)}\)</span> is provided here to understand the use of the probability for observing the evolution of the mean premium.</p>
<p><strong>Definition:</strong> Let <span class="math inline">\(p_{ij} = \Pr ({X_{n + 1}} = j|{X_n} = i)\)</span> be a <strong><em>one-step transition probability</em></strong> from state <span class="math inline">\(i\)</span> to state <span class="math inline">\(j\)</span>, and <span class="math inline">\(p_{ij}^{(n)} = \Pr ({X_n} = j|{X_0} = i)\)</span>, <span class="math inline">\(n = 1,2,...\)</span>, be an n-step transition probability from state <span class="math inline">\(i\)</span> to state <span class="math inline">\(j\)</span>. The probability <span class="math inline">\(p_{ij}^{(n)}\)</span> can be obtained using the <span class="math inline">\(n\)</span>th power of transition matrix <span class="math inline">\({\bf{P}}\)</span>, which is <span class="math inline">\({\bf{P}^n}.\)</span></p>
<p><strong><em>Example 6</em></strong></p>
<p><em>Observe the premiums in 20 years under the NCD system in Malaysia, assuming that the probability of claims is Poisson distributed with parameter</em> <span class="math inline">\(\lambda = 0.10\)</span> <em>and the premium prior to implementing the NCD is</em> <span class="math inline">\(m = 100\)</span><em>.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>Under the Malaysian NCD, we use the Poisson probability,</em> <span class="math inline">\(p_k = \frac{e^{ - 0.1}{(0.1)}^k}{k!}\)</span><em>, only for</em> <span class="math inline">\(k = 0,1.\)</span> <em>Therefore, the transition matrix in the first year is:</em></p>
<p><span class="math display">\[
{\bf{P}^{(1)}} = 
\left[{\begin{array}{*{20}{c}}
{0.0952}&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;{0.9048}&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;{0.9048}&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;0&amp;{0.9048}\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;0&amp;{0.9048}
\end{array}} \right]
\]</span></p>
<p><em>The premium in the first year, after implementing the NCD, is:</em></p>
<p><span class="math display">\[
\begin{aligned} 
&amp;= \sum\limits_j \text{(premium)} \times 
\text{(average proportion in class } j) \times \text{(1 - NCD in class }j) \\
&amp;= m\left[ \frac{\sum\limits_i {p_{i0}}}{6}{(1)} +
\frac{\sum\limits_i {p_{i1}}}{6}{(1 - 0.25)} + \ldots +
\frac{\sum\limits_i {p_{i5}}}{6}{(1 - 0.55)} \right]\\
&amp;=
100[0.0952(1) + 0.1508(0.75) + \cdots + 0.3016(0.45)]\\
&amp;= 62.55.
\end{aligned}
\]</span></p>
<p><em>Using similar steps, the premium in the</em> <span class="math inline">\(n\)</span><em>-th year for</em> <span class="math inline">\(n = 1,2,...,20\)</span> <em>can be observed. From R program, the premiums in 20 years are:</em></p>
<p><em>62.55, 59.87, 58.06, 57.06, 56.58, 56.58, 56.58, 56.58, 56.58, 56.58,</em></p>
<p><em>56.58, 56.58, 56.58, 56.58, 56.58, 56.58, 56.58, 56.58, 56.58, 56.58.</em></p>
</div>
<div id="r-program-for-premium-evolution" class="section level3">
<h3><span class="header-section-number">12.4.4</span> R Program for Premium Evolution</h3>
<p>The following R program can be used to find the premium in the <em>n-</em>th year and the premiums in 20 years under the NCD system in Malaysia (to find the solution in Example 6).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#create transition matrix</span>
entries=<span class="kw">c</span>(<span class="fl">0.0952</span>,<span class="fl">0.9048</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.0952</span>,<span class="dv">0</span>,<span class="fl">0.9048</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.0952</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9048</span>,<span class="dv">0</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.0952</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9048</span>,<span class="dv">0</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.0952</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9048</span>,
<span class="op">+</span><span class="st"> </span><span class="fl">0.0952</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="fl">0.9048</span>)
TP=<span class="kw">matrix</span>(entries,<span class="dt">nrow=</span><span class="dv">6</span>,<span class="dt">byrow=</span><span class="ot">TRUE</span>)
TP</code></pre></div>
<pre><code>##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]
## [1,] 0.0952 0.9048 0.0000 0.0000 0.0000 0.0000
## [2,] 0.0952 0.0000 0.9048 0.0000 0.0000 0.0000
## [3,] 0.0952 0.0000 0.0000 0.9048 0.0000 0.0000
## [4,] 0.0952 0.0000 0.0000 0.0000 0.9048 0.0000
## [5,] 0.0952 0.0000 0.0000 0.0000 0.0000 0.9048
## [6,] 0.0952 0.0000 0.0000 0.0000 0.0000 0.9048</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#create function for nth power of square matrix</span>
powA =<span class="st"> </span><span class="cf">function</span>(n) { 
  <span class="cf">if</span> (n<span class="op">==</span><span class="dv">1</span>) <span class="kw">return</span> (TP)
  <span class="cf">if</span> (n<span class="op">==</span><span class="dv">2</span>) <span class="kw">return</span> (TP<span class="op">%*%</span>TP)
  <span class="cf">if</span> (n<span class="op">&gt;</span><span class="dv">2</span>) <span class="kw">return</span> ( TP<span class="op">%*%</span><span class="kw">powA</span>(n<span class="op">-</span><span class="dv">1</span>)) }

<span class="co">#example for n=3</span>
<span class="kw">powA</span>(<span class="dv">3</span>)</code></pre></div>
<pre><code>##        [,1]       [,2]       [,3]      [,4]      [,5]      [,6]
## [1,] 0.0952 0.08613696 0.07793672 0.7407263 0.0000000 0.0000000
## [2,] 0.0952 0.08613696 0.07793672 0.0000000 0.7407263 0.0000000
## [3,] 0.0952 0.08613696 0.07793672 0.0000000 0.0000000 0.7407263
## [4,] 0.0952 0.08613696 0.07793672 0.0000000 0.0000000 0.7407263
## [5,] 0.0952 0.08613696 0.07793672 0.0000000 0.0000000 0.7407263
## [6,] 0.0952 0.08613696 0.07793672 0.0000000 0.0000000 0.7407263</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#define NCD percentage</span>
NCD=<span class="kw">c</span>(<span class="dv">1</span>,.<span class="dv">75</span>,.<span class="dv">7</span>,.<span class="dv">6167</span>,.<span class="dv">55</span>,.<span class="dv">45</span>)

<span class="co">#create function for premium in nth year</span>
p=<span class="kw">numeric</span>(<span class="dv">0</span>)
prem=<span class="cf">function</span>(n){
  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(NCD))
  p[j]=<span class="kw">mean</span>(<span class="kw">powA</span>(n)[,j])
  <span class="op">+</span><span class="st"> </span><span class="dv">100</span><span class="op">*</span><span class="kw">sum</span>(p<span class="op">*</span>NCD)}

<span class="co">#example for n=3</span>
<span class="kw">prem</span>(<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] 58.06106</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#provide premiums for 20 years</span>
premium=<span class="kw">numeric</span>(<span class="dv">0</span>)
<span class="cf">for</span> (n <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">20</span>)
premium[n]=<span class="kw">prem</span>(n)
<span class="kw">round</span>(premium,<span class="dv">2</span>)</code></pre></div>
<pre><code>##  [1] 62.55 59.87 58.06 57.06 56.58 56.58 56.58 56.58 56.58 56.58 56.58
## [12] 56.58 56.58 56.58 56.58 56.58 56.58 56.58 56.58 56.58</code></pre>
<p><strong><em>Example 7</em></strong></p>
<p><em>Observe the premiums in 20 years under the NCD system in Brazil, assuming that the probability of</em> <span class="math inline">\(k\)</span> <em>successive years of claims is</em> <span class="math inline">\(p_k = \frac{e^{ - 0.1}{(0.1)}^k}{{k!}},{\rm{ }}k = 0,1,2,.....\)</span>, <em>and</em> <em>the premium prior to implementing the NCD is</em> <span class="math inline">\(m = 100\)</span><em>.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>The transition matrix for the NCD system in Brazil is:</em></p>
<p><span class="math display">\[
{\bf P} = \left[
{\begin{array}{*{20}{c}}
{0.0952}&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0\\\\
{0.0047}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0\\\\
{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0&amp;0\\\\
{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}&amp;0\\\\
{0.0000}&amp;{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;0&amp;{0.9048}\\\\
{0.0000}&amp;{0.0000}&amp;{0.0000}&amp;{0.0002}&amp;{0.0045}&amp;{0.0905}&amp;{0.9048}
\end{array}} \right]
\]</span></p>
<p><em>Using R program the premiums in 20 years are:</em></p>
<p><em>76.69, 73.76, 71.31, 69.38, 67.92, 66.93, 66.40, 66.05, 65.88, 65.78,</em></p>
<p><em>65.72, 65.69, 65.67, 65.66, 65.66, 65.66, 65.66, 65.65, 65.65, 65.65.</em></p>
<p>The results in Examples 6-7 allow us to observe the evolution of premium for the NCD systems in Malaysia and Brazil assuming that the number of successive years of claims is Poisson distributed with parameter <span class="math inline">\(\lambda = 0.10\)</span>, and the premium prior to implementing the NCD is <span class="math inline">\(m = 100\)</span>. The evolutions of premiums for both countries are provided in Table 4, and are shown graphically in Figure <a href="C-BonusMalus.html#fig:PremEvolution">12.4</a>.</p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 4: Evolution of premium (Malaysia and Brazil)}\\
\begin{array}{*{20}c}
\hline
\text{year} &amp; \text{premium} &amp; \text{premium} &amp; \text{year} &amp; \text{premium} &amp; \text{premium} &amp; \\
&amp; \text{Malaysia} &amp; \text{Brazil} &amp; &amp; \text{Malaysia} &amp; \text{Brazil} \\
\hline\\
    0     &amp; 100   &amp; 100   &amp; 11    &amp; 56.58 &amp; 65.72 \\
    1     &amp; 62.55 &amp; 76.69 &amp; 12    &amp; 56.58 &amp; 65.69 \\
    2     &amp; 59.87 &amp; 73.76 &amp; 13    &amp; 56.58 &amp; 65.67 \\
    3     &amp; 58.06 &amp; 71.31 &amp; 14    &amp; 56.58 &amp; 65.66 \\
    4     &amp; 57.06 &amp; 69.38 &amp; 15    &amp; 56.58 &amp; 65.66 \\
    5     &amp; 56.58 &amp; 67.92 &amp; 16    &amp; 56.58 &amp; 65.66 \\
    6     &amp; 56.58 &amp; 66.93 &amp; 17    &amp; 56.58 &amp; 65.66 \\
    7     &amp; 56.58 &amp; 66.40 &amp; 18    &amp; 56.58 &amp; 65.65 \\
    8     &amp; 56.58 &amp; 66.05 &amp; 19    &amp; 56.58 &amp; 65.65 \\
    9     &amp; 56.58 &amp; 65.88 &amp; 20    &amp; 56.58 &amp; 65.65 \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<div class="figure" style="text-align: center"><span id="fig:PremEvolution"></span>
<img src="Figures/FigureEvolution.png" alt="Evolution of premium (Malaysia and Brazil)" width="80%" />
<p class="caption">
Figure 12.4: Evolution of premium (Malaysia and Brazil)
</p>
</div>
</div>
<div id="convergence-rate" class="section level3">
<h3><span class="header-section-number">12.4.5</span> Convergence Rate</h3>
<p>Sometimes we are interested to know the variation between the probability in the <em>n</em>-th year, <span class="math inline">\(p_{ij}^{(n)}\)</span>, and the stationary probability, <span class="math inline">\(\pi _j\)</span>. The variation between the probabilities can be measured using:</p>
<p><span class="math display">\[\left| {average(p_{ij}^{(n)}) - {\pi _j}} \right|\]</span>.</p>
<p>Therefore, the total variation can be measured by the sum of variation in all classes:</p>
<p><span class="math display">\[\sum\limits_j {\left| {average(p_{ij}^{(n)}) - {\pi _j}} \right|}\]</span>.</p>
<p>The total variation is also called the <a href="#" class="tooltip" style="color:green"><em>convergence rate</em><span style="font-size:8pt">After n transitions, the sum of variation between the probability in each state vs. the stationary probability</span></a> because it measures the convergence rate after <span class="math inline">\(n\)</span> years (or <span class="math inline">\(n\)</span> transitions).</p>
<p><strong><em>Example 8</em></strong></p>
<p><em>Provide the total variations (convergence rate) in 20 years under the NCD system in Malaysia, assuming that the probability of claims is Poisson distributed with parameter</em> <span class="math inline">\(\lambda = 0.10\)</span><em>.</em></p>
<p><strong><em>Solution</em></strong></p>
<p><em>Using R program, the stationary probabilities are:</em></p>
<p><span class="math display">\[
\left[ {\begin{array}{*{20}{c}}
{{\pi _0}}\\\\{{\pi_1}}\\\\{{\pi _2}}\\\\
{{\pi _3}}\\\\{{\pi _4}}\\\\{{\pi_5}}
\end{array}} \right]
= \left[ {\begin{array}{*{20}{c}}
{0.0952}\\\\{0.0861}\\\\{0.0779}\\\\
{0.0705}\\\\{0.0638}\\\\{0.6064}
\end{array}} \right]
\]</span></p>
<p><em>The transition matrix in the first year is:</em></p>
<p><span class="math display">\[
{\bf{P}}^{(1)} = \left[
{\begin{array}{*{20}{c}}
{0.0952}&amp;{0.9048}&amp;0&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;{0.9048}&amp;0&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;{0.9048}&amp;0&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;{0.9048}&amp;0\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;0&amp;{0.9048}\\\\
{0.0952}&amp;0&amp;0&amp;0&amp;0&amp;{0.9048}
\end{array}} \right]
\]</span></p>
<p><em>The variation can be computed as:</em></p>
<p><span class="math display">\[
\begin{array}{l}
\left| {\sum\limits_i {\frac{p_{i0}^{}}{6}} - {\pi _0}} \right| = 0\\\\
\left|{\sum\limits_i {\frac{p_{i1}^{}}{6}} - {\pi _1}} \right| =
0.0647\\\\
\vdots \\\\
\left| {\sum\limits_i
\frac{p_{i5}}{6} - {\pi _5}} \right| =
.3048
\end{array}
\]</span></p>
<p><em>Therefore, the total variation in the first year is</em> <span class="math inline">\(\sum\limits_j {\left| {\sum\limits_i {\frac{p_{ij}}{6} - {\pi _j}} } \right|} = 0.6096\)</span><em>.</em></p>
<p><em>Using R program, the total variations (or convergence rate) in 20 years are:</em></p>
<p><em>0.6096, 0.3941, 0.2252, 0.0958, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.</em></p>
</div>
<div id="r-program-for-convergence-rate" class="section level3">
<h3><span class="header-section-number">12.4.6</span> R Program for Convergence Rate</h3>
<p>The following R program can be used to calculate the total variation in the <span class="math inline">\(n\)</span>th year, and the total variations (convergence rates) in 20 years under the NCD system in Malaysia (the solution in Example 8).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#transition matrix</span>
TP</code></pre></div>
<pre><code>##        [,1]   [,2]   [,3]   [,4]   [,5]   [,6]
## [1,] 0.0952 0.9048 0.0000 0.0000 0.0000 0.0000
## [2,] 0.0952 0.0000 0.9048 0.0000 0.0000 0.0000
## [3,] 0.0952 0.0000 0.0000 0.9048 0.0000 0.0000
## [4,] 0.0952 0.0000 0.0000 0.0000 0.9048 0.0000
## [5,] 0.0952 0.0000 0.0000 0.0000 0.0000 0.9048
## [6,] 0.0952 0.0000 0.0000 0.0000 0.0000 0.9048</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># stationary probability</span>
SP=<span class="kw">eigen</span>(<span class="kw">t</span>(TP))<span class="op">$</span>vectors[,<span class="dv">1</span>]<span class="op">/</span><span class="kw">sum</span>(<span class="kw">eigen</span>(<span class="kw">t</span>(TP))<span class="op">$</span>vectors[,<span class="dv">1</span>])
SP</code></pre></div>
<pre><code>## [1] 0.09520000+0i 0.08613696+0i 0.07793672+0i 0.07051715+0i 0.06380391+0i
## [6] 0.60640526+0i</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#create function for total variation in nth year</span>
TV=<span class="cf">function</span>(n)
{dif=<span class="kw">numeric</span>(<span class="dv">0</span>)
<span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(SP))
dif[j]=<span class="kw">abs</span>(<span class="kw">mean</span>(<span class="kw">powA</span>(n)[,j])<span class="op">-</span>SP[j])
<span class="op">+</span><span class="st"> </span><span class="kw">sum</span>(dif)}

<span class="co">#example for n=1</span>
<span class="kw">TV</span>(<span class="dv">1</span>)</code></pre></div>
<pre><code>## [1] 0.6096105</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#provide total variations (convergence rate) in 20 years</span>
tot.var=<span class="kw">numeric</span>(<span class="dv">0</span>)
<span class="cf">for</span> (n <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">20</span>)
tot.var[n]=<span class="kw">TV</span>(n)
<span class="kw">round</span>(tot.var,<span class="dv">4</span>)</code></pre></div>
<pre><code>##  [1] 0.6096 0.3941 0.2252 0.0958 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
## [11] 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000</code></pre>
<p><strong><em>Example 9</em></strong></p>
<p><em>Provide the total variations (or convergence rate) in 20 years under the NCD system in Brazil, assuming that the number of successive years of claims is distributed as Poisson with parameter</em> <span class="math inline">\(\lambda = 0.10\)</span></p>
<p><strong><em>Solution</em></strong></p>
<p><em>Using R program, the total variations (or convergence rates) in 20 years for the NCD system in Brazil are:</em></p>
<p><em>1.2617, 1.0536, 0.8465, 0.6412, 0.4362, 0.2316, 0.1531, 0.0747, 0.0480, 0.0232,</em></p>
<p><em>0.0145, 0.0071, 0.0043, 0.0021, 0.0013, 0.0006, 0.0004, 0.0002, 0.0001, 0.0001.</em></p>
<p>Examples 8-9 provide the degree of convergence for two different BMS (two different countries). The Malaysian BMS reaches full stationary only after four years, while the BMS in Brazil takes a longer period. As mentioned in Lemaire (1998), a more sophisticated BMS would converge more slowly, and is considered as a drawback as it takes a longer period to stabilize. The main objective of a BMS is to separate the good drivers from the bad drivers, and thus, it is desirable to have a classification process that can be finalized (or stabilized) as soon as possible.</p>
</div>
</div>
<div id="S:PremRtg" class="section level2">
<h2><span class="header-section-number">12.5</span> BMS and Premium Rating</h2>
<div id="premium-rating" class="section level3">
<h3><span class="header-section-number">12.5.1</span> Premium Rating</h3>
<p>Premium rating is the process of establishing premium rates in an insurance system, or other risk transfer mechanisms. The process involves a number of considerations such as statistical methods, marketing goals, competition and legal restrictions. Premium rating should fulfill four basic objectives generally agreed among the actuaries; producing ‘fair’ premium rates whereby high risks insureds pay higher premium and vice versa, providing sufficient funds for paying incurred losses and expenses, providing adequate margin for adverse deviation, and producing reasonable returns to insurers.</p>
<p>Before we discuss the application of BMS in premium rating, a brief discussion of the Poisson and negative binomial regression models are provided here. The Poisson regression has been widely used for fitting count (or frequency) data in insurance area. The negative binomial regression model can be used for fitting count (or frequency) data with <a href="#" class="tooltip" style="color:green"><em>overdispersion</em><span style="font-size:8pt">Phenomenon where the variance of data is larger than what is modeled</span></a>, which is a situation when the variance is larger than the mean. However, students are encouraged to refer to textbooks on <a href="#" class="tooltip" style="color:green"><em>GLM</em><span style="font-size:8pt">Generalized linear model</span></a>s or regression models available in the literature for a more comprehensive knowledge on the related subjects.</p>
</div>
<div id="frequency-model-poisson-and-negative-binomial-regressions" class="section level3">
<h3><span class="header-section-number">12.5.2</span> Frequency Model – Poisson and Negative Binomial Regressions</h3>
<p>Let <span class="math inline">\({({Y_1},{Y_2},...,{Y_n})^T}\)</span> be the vector of count random variables and <span class="math inline">\(n\)</span> be the sample size. The probability mass function (p.m.f.) for <a href="#" class="tooltip" style="color:green"><em>Poisson regression model</em><span style="font-size:8pt">Type of regression model used for fitting data with an integral (count) response variable with mean equal to the variance</span></a> is,</p>
<p><span class="math display">\[\Pr ({Y_i} = {y_i})
\begin{array}{*{20}{c}}
= \frac{{{\exp(- {\mu _i})}{\mu _i}^{y_i}}}{y_i{!}}&amp;{y_i = 0,1,...}
\end{array}
\]</span></p>
<p>with mean and variance <span class="math inline">\(E({Y_i}) = Var({Y_i}) = {\mu _i}\)</span>. To take into account non-negative values, the mean, or the fitted value, is assumed to follow a log link, <span class="math inline">\(E({Y_i}) = {\mu _i} = \exp ({\bf x}_{\bf i}{\bf &#39;\beta })\)</span>, where <span class="math inline">\({\bf{x}}_{\bf i}\)</span> denotes the vector of explanatory variables and <span class="math inline">\({\bf \beta}\)</span> is the vector of regression parameters. The maximum likelihood estimates can be obtained by maximizing the log likelihood.</p>
<p>The p.m.f. for <a href="#" class="tooltip" style="color:green"><em>negative binomial regression model</em><span style="font-size:8pt">Type of regression model used for fitting data with an integral (count) response variable and can account for variance greater than the mean</span></a> is,</p>
<p><span class="math display">\[
\Pr ({Y_i} = {y_i}) = \frac{{\Gamma ({y_i} +
v)}}{y_i{!}\Gamma (v)}
\left( \frac{v}{v + {\mu _i}}
\right)^v
\left( \frac{\mu _i}{v + {\mu _i}}
\right)^{y_i},{y_i} = 0,1,2,...,
\]</span></p>
<p>where the mean is <span class="math inline">\(E({Y_i}) = {\mu _i}\)</span>, the variance is <span class="math inline">\(Var({Y_i}) = {\mu _i}(1 + {v^{ - 1}}{\mu _i}) = {\mu _i}(1 + a{\mu _i})\)</span>, and <span class="math inline">\({v^{ - 1}} = a\)</span> denotes the dispersion parameter. The NB regression model reduce to the Poisson regression model in the limit as <span class="math inline">\(a \to 0\)</span>, and display overdispersion when <span class="math inline">\(a &gt; 0\)</span>. The mean can also be assumed to follow the log link, <span class="math inline">\(E({Y_i}) = {\mu _i} = \exp ({{\bf x}_{\bf i}{\bf{&#39;\beta }}})\)</span>, and the maximum likelihood estimates can be obtained by maximizing the log likelihood.</p>
</div>
<div id="premium-rating-with-bonus-malus-data" class="section level3">
<h3><span class="header-section-number">12.5.3</span> Premium Rating with Bonus-Malus Data</h3>
<p>Under this section, we will consider the statistical approach of obtaining premium rates using count data (frequency data) that provides bonus-malus information on the risk profiles of the insureds.</p>
<p><strong>Example 10</strong></p>
<p>Consider the Canadian private automobile liability insurance data from Bailey and Simon (1960). The data provides information on the number of claims incurred and exposures (expressed in terms of number of earned car years). The data is classified into two rating factors; merit rating and class rating. Altogether, there are twenty <span class="math inline">\((4 \times 5)\)</span> <a href="#" class="tooltip" style="color:green"><em>cross-classified rating classes</em><span style="font-size:8pt">Table that combines the effects of multiple rating classifications</span></a> of claim frequencies (20 count data). Table 5 provides the description of the two rating factors. It can be seen that merit rating provides information on the number of accident-free years, and thus, the information can be used as bonus-malus information. Using the Canadian automobile insurance data:</p>
<ol style="list-style-type: lower-roman">
<li><p>Fit the count data using Poisson regression model.</p></li>
<li><p>Calculate the premium assuming that the claim severity is 1000 for all rating classes.</p></li>
<li><p>Build a simple premium table, and suggest the percentage of discounts (or loadings) for the premiums if the BMS is to be considered.</p></li>
</ol>
<p><span class="math display">\[
\begin{matrix}
\text{Table 5: Rating factors (Canadian data)}\\
\begin{array}{*{20}c}
\hline
\text{Merit} &amp; \text{Class}\\
\hline\\
\text{A = licensed, accident-free ≥ 3 years } &amp; \text{1 = pleasure, no male operator &lt; 25 } \\
\text{X = licensed, accident-free 2 years } &amp; \text{2 = pleasure, non-principal male operator &lt; 25 } \\
\text{Y = licensed, accident-free 1 year } &amp; \text{3 = business use } \\
\text{B = others} &amp; \text{4 = unmarried owner / principal operator &lt; 25} \\
&amp; \text{5 = married owner / principal operator &lt; 25 } \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><strong>Solution</strong></p>
<ol style="list-style-type: lower-roman">
<li><p>Table 6 provides the parameter estimates (and standard errors) for the Poisson regression model which is fitted to the count data.</p></li>
<li><p>The premiums are calculated by multiplying the fitted frequencies with the claim severities. The fitted frequency is obtained by dividing the fitted count with the exposure. The fitted count, <span class="math inline">\(E({Y_i}) = {\mu _i} = {\hat y_i}\)</span>, is the fitted value obtained from the Poisson regression model. The premiums for all rating classes, are shown in Table 7.</p></li>
<li><p>Let the premium classified under merit B be the base premium. The premium relativities and the percentage of discounts for each rating class can be calculated, and the values are shown in Table 8. A simple premium table, which provides the percentage of discounts based on the number of accident-free years, can be constructed and is shown in Table 9. The discounts can be suggested for implementing the BMS.</p></li>
</ol>
<p><span class="math display">\[
\begin{matrix}
\text{Table 6: Poisson regression model (Canadian data)}\\
\begin{array}{*{20}c}
\hline
\text{Regression parameter} &amp; \text{est.} &amp; \text{std. error} &amp; p\text{ -value} \\
\hline\\
\text{Intercept} &amp; {-2.53} &amp; {0.00} &amp; {0.00} \\
\text{Class 2} &amp; {0.30} &amp; {0.01} &amp; {0.00} \\
\text{Class 3} &amp; {0.47} &amp; {0.01} &amp; {0.00} \\
\text{Class 4} &amp; {0.53} &amp; {0.01} &amp; {0.00} \\
\text{Class 5} &amp; {0.22} &amp; {0.01} &amp; {0.00} \\
\text{Merit X} &amp; {0.27} &amp; {0.01} &amp; {0.00} \\
\text{Merit Y} &amp; {0.36} &amp; {0.01} &amp; {0.00} \\
\text{Merit B} &amp; {0.49} &amp; {0.00} &amp; {0.00} \\
          &amp;       &amp;       &amp;  \\
\text{Log }L &amp; {-394.96} &amp;       &amp;  \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 7: Fitted count, fitted frequency and premium (Canadian data)}\\
\begin{array}{*{20}c}
\hline
\text{Class} &amp; \text{Merit} &amp; &amp; &amp; \text{Fitted frequency}  &amp; \text{Premium}  \\
\text{rating} &amp; \text{rating} &amp; \text{Fitted count} &amp; \text{Exposure} &amp; \text{(count/exposure)} &amp; \text{(frequency x 1000)}\\
\hline\\
    1     &amp; \text{A} &amp; 219950 &amp; 2757520 &amp; 0.08  &amp; 80 \\
    1     &amp; \text{X} &amp; 13688 &amp; 130706 &amp; 0.1   &amp; 105 \\
    1     &amp; \text{Y} &amp; 18608 &amp; 163544 &amp; 0.11  &amp; 114 \\
    1     &amp; \text{B} &amp; 35773 &amp; 273944 &amp; 0.13  &amp; 131 \\
    2     &amp; \text{A} &amp; 14052 &amp; 130535 &amp; 0.11  &amp; 108 \\
    2     &amp; \text{X} &amp; 1022  &amp; 7233  &amp; 0.14  &amp; 141 \\
    2     &amp; \text{Y} &amp; 1494  &amp; 9726  &amp; 0.15  &amp; 154 \\
    2     &amp; \text{B} &amp; 3790  &amp; 21504 &amp; 0.18  &amp; 176 \\
    3     &amp; \text{A} &amp; 31547 &amp; 247424 &amp; 0.13  &amp; 128 \\
    3     &amp; \text{X} &amp; 2656  &amp; 15868 &amp; 0.17  &amp; 167 \\
    3     &amp; \text{Y} &amp; 3705  &amp; 20369 &amp; 0.18  &amp; 182 \\
    3     &amp; \text{B} &amp; 7862  &amp; 37666 &amp; 0.21  &amp; 209 \\
    4     &amp; \text{A} &amp; 21170 &amp; 156871 &amp; 0.13  &amp; 135 \\
    4     &amp; \text{X} &amp; 3137  &amp; 17707 &amp; 0.18  &amp; 177 \\
    4     &amp; \text{Y} &amp; 4060  &amp; 21089 &amp; 0.19  &amp; 193 \\
    4     &amp; \text{B} &amp; 12534 &amp; 56730 &amp; 0.22  &amp; 221 \\
    5     &amp; \text{A} &amp; 6346  &amp; 64130 &amp; 0.1   &amp; 99 \\
    5     &amp; \text{X} &amp; 525   &amp; 4039  &amp; 0.13  &amp; 130 \\
    5     &amp; \text{Y} &amp; 687   &amp; 4869  &amp; 0.14  &amp; 141 \\
    5     &amp; \text{B} &amp; 1393  &amp; 8601  &amp; 0.16  &amp; 162 \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 8: Premium relativities (Canadian data)}\\
\begin{array}{*{20}c}
\hline
\text{Class} &amp; \text{Merit} &amp; \text{Premium} &amp; \text{Premium relativity} &amp; \text{Discount} \\
\hline\\
    1     &amp; \text{A} &amp; 80    &amp; 0.61  &amp; 39 \\
          &amp; \text{X} &amp; 105   &amp; 0.80 &amp; 20 \\
          &amp; \text{Y} &amp; 114   &amp; 0.87  &amp; 13 \\
          &amp; \text{B} &amp; 131   &amp; 1.00   &amp; 0 \\
    2     &amp; \text{A} &amp; 108   &amp; 0.61  &amp; 39 \\
          &amp; \text{X} &amp; 141   &amp; 0.80  &amp; 20 \\
          &amp; \text{Y} &amp; 154   &amp; 0.88  &amp; 13 \\
          &amp; \text{B} &amp; 176   &amp; 1.00     &amp; 0 \\
    3     &amp; \text{A} &amp; 128   &amp; 0.61  &amp; 39 \\
          &amp; \text{X} &amp; 167   &amp; 0.80  &amp; 20 \\
          &amp; \text{Y} &amp; 182   &amp; 0.87  &amp; 13 \\
          &amp; \text{B} &amp; 209   &amp; 1.00     &amp; 0 \\
    4     &amp; \text{A} &amp; 135   &amp; 0.61  &amp; 39 \\
          &amp; \text{X} &amp; 177   &amp; 0.80   &amp; 20 \\
          &amp; \text{Y} &amp; 193   &amp; 0.87  &amp; 13 \\
          &amp; \text{B} &amp; 221   &amp; 1.00     &amp; 0 \\
    5     &amp; \text{A} &amp; 99    &amp; 0.61  &amp; 39 \\
          &amp; \text{X} &amp; 130   &amp; 0.80   &amp; 20 \\
          &amp; \text{Y} &amp; 141   &amp; 0.87  &amp; 13 \\
          &amp; \text{B} &amp; 162   &amp; 1.00  &amp; 0 \\\\
\hline
\end{array}
\end{matrix}\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 9: Premium rates and BMS (Canadian data)}\\
\begin{array}{*{20}c}
\hline
\text{Class} &amp; \text{Premium} &amp; \text{Years of} &amp; \text{Discount for} \\
&amp; &amp; \text{accident-free} &amp; \text{bonus-malus }\\
\hline\\
    1     &amp; 131   &amp; {3+} &amp; 39 \\
          &amp;       &amp; 2     &amp; 20 \\
          &amp;       &amp; 1     &amp; 13 \\
          &amp;       &amp; 0     &amp; 0 \\
    2     &amp; 176   &amp; {3+} &amp; 39 \\
          &amp;       &amp; 2     &amp; 20 \\
          &amp;       &amp; 1     &amp; 13 \\
          &amp;       &amp; 0     &amp; 0 \\
    3     &amp; 209   &amp; {3+} &amp; 39 \\
          &amp;       &amp; 2     &amp; 20 \\
          &amp;       &amp; 1     &amp; 13 \\
          &amp;       &amp; 0     &amp; 0 \\
    4     &amp; 221   &amp; {3+} &amp; 39 \\
          &amp;       &amp; 2     &amp; 20 \\
          &amp;       &amp; 1     &amp; 13 \\
          &amp;       &amp; 0     &amp; 0 \\
    5     &amp; 162   &amp; {3+} &amp; 39 \\
          &amp;       &amp; 2     &amp; 20 \\
          &amp;       &amp; 1     &amp; 13 \\
          &amp;       &amp; 0     &amp; 0 \\\\
\hline
\end{array}
\end{matrix}\]</span></p>
</div>
<div id="premium-rating-without-bonus-malus-data" class="section level3">
<h3><span class="header-section-number">12.5.4</span> Premium Rating without Bonus-Malus Data</h3>
<p>Under this section, we will consider the statistical approach of obtaining premium rates using count data that does not provide bonus-malus information on the risk profiles of the insureds.</p>
<p><strong>Example 11</strong></p>
<p>The dataset for private car Own Damage (OD) claim count in Malaysia (Zamani and Ismail 2012, Ismail and Zamani 2013) is considered here. The data is based on 1.01 million private car policies for a three-year period of 2001-2003. The exposures are expressed in car-year units. Table 10 shows the rating factors for the claim count data. Altogether, there are <span class="math inline">\(5 \times 5 \times 5 \times 5 = 625\)</span> cross-classified rating classes of claim frequencies (625 count data). However, the number of rating classes (sample size) reduces to 547 after excluding count data with zero exposure. It can be seen from the description in Table 10 that the data does not provide information on the number of claim-free years (bonus-malus information). Using the Malaysian private car insurance data:</p>
<ol style="list-style-type: lower-roman">
<li><p>Fit the count data using Poisson and negative binomial regression models. Compare both models and suggest a preferred model for the data.</p></li>
<li><p>Calculate the premium assuming that the claim severity is MYR 1000 (Ringgit Malaysia) for all rating classes.</p></li>
<li><p>Build a premium table, assuming that the NCD is to be implemented.</p></li>
</ol>
<p><span class="math display">\[
\begin{matrix}
\text{Table 10: Rating factors (Malaysian data)}\\
\begin{array}{*{20}c}
\hline
\text{Rating factors} &amp; \text{Description} \\
\hline\\
    \text{Vehicle age} &amp; \text{0-1 year } \\
          &amp; \text{2-3 years} \\
          &amp; \text{4-5 years} \\
          &amp; \text{6-7 years} \\
          &amp; \text{8+ years} \\
    \text{Vehicle c.c.} &amp; \text{0-1000} \\
          &amp; \text{1001-1300} \\
          &amp; \text{1301-1500} \\
          &amp; \text{1501-1800} \\
          &amp; \text{1801+} \\
    \text{Vehicle make} &amp; \text{Local type 1} \\
          &amp; \text{Local type 2} \\
          &amp; \text{Foreign type 1} \\
          &amp; \text{Foreign type 2} \\
          &amp; \text{Foreign type 3} \\
    \text{Location} &amp; \text{North} \\
          &amp; \text{East} \\
          &amp; \text{Central} \\
          &amp; \text{South} \\
          &amp; \text{East Malaysia} \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><strong>Solution</strong></p>
<ol style="list-style-type: lower-roman">
<li><p>Table 11 shows the parameter estimates (and standard errors) for the fitted Poisson and negative binomial regression models. The results indicate that the regression parameters of all models have similar estimates. The likelihood ratio for testing overdispersion between the Poisson and the NB models is 2844.14, indicating that the data is overdispersed and the NB is a better model. The <a href="#" class="tooltip" style="color:green"><em>AIC</em><span style="font-size:8pt">Akaike’s information criterion</span></a> and <a href="#" class="tooltip" style="color:green"><em>BIC</em><span style="font-size:8pt">Bayesian information criterion</span></a> also indicate that the NB is a better model. Table 12 shows the parameter estimates (and standard errors) for the fitted negative binomial regression model with significant covariates (covariates with <span class="math inline">\(p\)</span>-values larger than 0.10 are excluded). The NB model in Table 12 is suggested as the preferred model for the data.</p></li>
<li><p>The premiums are calculated by multiplying the fitted frequencies with the claim severities. The premiums for the first 25 rating classes (vehicle age: 0-1 year and vehicle make: local-type 1) are shown in Table 13.</p></li>
<li><p>The Malaysian NCD system have six discount classes (0%, 25%, 30%, 38.3%, 45% and 55%) for 0, 1, 2, 3, 4 and 5+ claim-free years. The final premium rates should be ‘inflated’ accordingly to take into account the NCD (discount entitlement) of each insured. We can use the stationary distribution to approximate the proportion of insureds in each NCD class (in the long run). Assume that the probability of a no-claim year for all NCD classes is 0.90. The stationary probabilities are (from Example 3):</p></li>
</ol>
<p><span class="math display">\[
{\pi_0} = 0.1000,\rm{ }{\pi _1} = 0.0900,\rm{ }{\pi
_2} = 0.0810,\rm{ }{\pi _3} = 0.0729,\rm{ }{\pi _4} =
0.0656,\rm{ }{\pi _5} = 0.5905
\]</span></p>
<p>which indicates that 10% of insureds eventually belong to class 0 (zero claim-free years), 9% of insureds eventually belong to class 1 (one claim-free year), and so forth, until 59% of insureds eventually belong to class 5 (or five successive claim-free years). After implementing the NCD, the premium (in the long run) will be reduced (on average) by the following factor:</p>
<p><span class="math display">\[
\begin{array}{l} 
= \sum\limits_j \text{(proportion of insureds in class }j)\text{(1 - NCD
in class }j) \\\\ 
= (0.1000)(1) + (0.0900)(1 - 0.25) + ... + (0.5905)(1 - 0.55)\\\\ 
= {0}{.570962}
\end{array}
\]</span></p>
<p>Therefore, the final premiums (after adjusting for the NCD) should be inflated by <span class="math inline">\(1 \div 0.57 = 1.75\)</span>. A premium table can be constructed based on the factor (1.75). The final premiums for the first 5 rating classes are shown in Table 14, and can be suggested for implementing the NCD.</p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 11: Poisson and negative binomial regression models (Malaysian data)}\\
\begin{array}{*{20}c}
\hline
\text{Parameters} &amp; \text{Poisson} &amp; \text{Poisson} &amp; \text{NB} &amp; \text{NB} \\
&amp; \text{Est.} &amp; {p}\text{ -value} &amp; \text{Est.} &amp; {p}\text{ -value} \\
\hline\\
    \text{Intercept} &amp; {-3.04} &amp; {0.00} &amp; -3.17 &amp; 0.00 \\
    \text{2-3 year} &amp; {0.51} &amp; {0.00} &amp; 0.57  &amp; 0.00 \\
    \text{4-5 year} &amp; {0.52} &amp; {0.00} &amp; 0.52  &amp; 0.00 \\
    \text{6-7 year} &amp; {0.43} &amp; {0.00} &amp; 0.40   &amp; 0.00 \\
    \text{8+ year} &amp; {0.24} &amp; {0.00} &amp; 0.28  &amp; 0.00 \\
    \text{1001-1300 cc} &amp; {-0.31} &amp; {0.00} &amp; -0.14 &amp; 0.00 \\
    \text{1301-1500 cc} &amp; {-0.16} &amp; {0.00} &amp; 0.08  &amp; 0.16 \\
    \text{1501-1800 cc} &amp; {0.14} &amp; {0.00} &amp; 0.25  &amp; 0.00 \\
    \text{1801+ cc} &amp; {0.12} &amp; {0.00} &amp; 0.34  &amp; 0.00 \\
    \text{Local type 2} &amp; {-0.46} &amp; {0.00} &amp; -0.30  &amp; 0.00 \\
    \text{Foreign type 1} &amp; {-0.21} &amp; {0.00} &amp; -0.31 &amp; 0.00 \\
    \text{Foreign type 2} &amp; {0.18} &amp; {0.00} &amp; 0.31  &amp; 0.00 \\
    \text{Foreign type 3} &amp; {-0.02} &amp; {0.43} &amp; -0.16 &amp; 0.04 \\
    \text{East} &amp; {0.35} &amp; {0.00} &amp; 0.30  &amp; 0.00 \\
    \text{Central} &amp; {0.32} &amp; {0.00} &amp; 0.31  &amp; 0.00 \\
    \text{South} &amp; {0.26} &amp; {0.00} &amp; 0.36  &amp; 0.00 \\
    \text{East Malaysia} &amp; {0.13} &amp; {0.00} &amp; 0.11  &amp; 0.08 \\
    {a} &amp; {-} &amp; {-} &amp; 0.13  &amp; 0.00 \\
          &amp;       &amp;       &amp;       &amp;  \\
    \text{Log likelihood} &amp; &amp; {-3,613.39} &amp;       &amp; -2191.32 \\
    \text{AIC} &amp; &amp; {7,260.79} &amp;       &amp; 4418.65 \\
    \text{BIC} &amp; &amp; {7,333.96} &amp;       &amp; 4496.13 \\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 12: Negative binomial regression model with significant covariates (Malaysian data)}\\
\begin{array}{*{20}c}
\hline
\text{Parameters} &amp; \text{Est.} &amp; p\text{ -value}\\
\hline \\
\text{Intercept} &amp; {-3.14} &amp; {0.00}\\
\text{2-3 year} &amp; {0.58} &amp; {0.00}\\
\text{4-5 year} &amp; {0.53} &amp; {0.00}\\
\text{6-7 year} &amp; {0.41} &amp; {0.00}\\
\text{8+ year} &amp; {0.29} &amp; {0.00}\\
\text{1001-1300 cc} &amp; {-0.17} &amp; {0.00}\\
\text{1501-1800 cc} &amp; {0.23} &amp; {0.00}\\
\text{1801+ cc} &amp; {0.32} &amp; {0.00}\\
\text{Local type 2} &amp; {-0.32} &amp; {0.00}\\
\text{Foreign type 1} &amp; {-0.31} &amp; {0.00}\\
\text{Foreign type 2} &amp; {0.31} &amp; {0.00}\\
\text{Foreign type 3} &amp; {-0.18} &amp; {0.02}\\
\text{East} &amp; {0.30} &amp; {0.00}\\
\text{Central} &amp; {0.31} &amp; {0.00}\\
\text{South} &amp; {0.36} &amp; {0.00}\\
\text{East Malaysia} &amp; {0.11} &amp; {0.08}\\
\alpha\,\text{(dispersion)} &amp; {0.13} &amp; {0.00}\\\\
\text{Log likelihood} &amp; &amp; {-2192.34}\\
\text{AIC} &amp; &amp; {4418.68}\\
\text{BIC} &amp; &amp; {4491.85}\\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 13: Premium rates (Malaysian data)}\\
\begin{array}{*{20}c}
\hline
\text{Vehicle} &amp; \text{Vehicle} &amp; \text{Vehicle} &amp; \text{location} &amp; \text{exposure} &amp; \text{Fitted}
&amp; \text{Premium}\\
\text{year} &amp; \text{cc} &amp; \text{make} &amp; &amp; &amp; \text{count}
&amp; \left(\frac{fitted\,count}{exposure} \times 1000 \right)\\
\hline\\
0-1\,\text{year} &amp; {0-1000} &amp; \text{local-1} &amp; \text{north} &amp; {34} &amp; {1} &amp; {29}\\
&amp; &amp; &amp; \text{east} &amp; {11} &amp; {1} &amp; {91}\\
&amp; &amp; &amp; \text{central} &amp; {184} &amp; {11} &amp; {60}\\
&amp; &amp; &amp; \text{south} &amp; {14} &amp; {1} &amp; {71}\\
&amp; &amp; &amp; \text{east Msia} &amp; {22} &amp; {1} &amp; {45}\\
&amp; &amp; \text{local-2} &amp; \text{north} &amp; {17881} &amp; {562} &amp; {31}\\
&amp; &amp; &amp; \text{east} &amp; {7581} &amp; {322} &amp; {42}\\
&amp; &amp; &amp; \text{central} &amp; {19699} &amp; {844} &amp; {43}\\
&amp; &amp; &amp; \text{south} &amp; {8268} &amp; {371} &amp; {45}\\
&amp; &amp; &amp; \text{east Msia} &amp; {12229} &amp; {429} &amp; {35}\\
&amp; &amp; \text{foreign-1} &amp; \text{north} &amp; {241} &amp; {8} &amp; {33}\\
&amp; &amp; &amp; \text{east} &amp; {44} &amp; {2} &amp; {45}\\
&amp; &amp; &amp; \text{central} &amp; {254} &amp; {11} &amp; {43}\\
&amp; &amp; &amp; \text{south} &amp; {35} &amp; {2} &amp; {57}\\
&amp; &amp; &amp; \text{east Msia} &amp; {113} &amp; {4} &amp; {35}\\
&amp; &amp; \text{foreign-2} &amp; \text{north} &amp; {64} &amp; {4} &amp; {63}\\
&amp; &amp; &amp; \text{east} &amp; {7} &amp; {1} &amp; {143}\\
&amp; &amp; &amp; \text{central} &amp; {164} &amp; {13} &amp; {79}\\
&amp; &amp; &amp; \text{south} &amp; {23} &amp; {2} &amp; {87}\\
&amp; &amp; &amp; \text{east Msia} &amp; {45} &amp; {1} &amp; {67}\\
&amp; &amp; \text{foreign-3} &amp; \text{north} &amp; {7512} &amp; {274} &amp; {36}\\
&amp; &amp; &amp; \text{east} &amp; {2747} &amp; {135} &amp; {49}\\
&amp; &amp; &amp; \text{central} &amp; {15551} &amp; {774} &amp; {50}\\
&amp; &amp; &amp; \text{south} &amp; {7408} &amp; {387} &amp; {52}\\
&amp; &amp; &amp; \text{east Msia} &amp; {6740} &amp; {274} &amp; {41}\\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><span class="math display">\[
\begin{matrix}
\text{Table 14: Premium, final premium and NCD (Malaysian data)}\\
\begin{array}{*{20}c}
\hline
\text{Vehicle} &amp; \text{Vehicle} &amp; \text{Vehicle} &amp; \text{location} &amp; \text{Premium} &amp; \text{Final} &amp; \text{Years of} &amp; \text{NCD}\\
\text{year} &amp; \text{cc} &amp; \text{make} &amp; &amp; &amp; \text{Premium}
&amp; \text{claim-free} &amp; \left( \% \right)\\
&amp; &amp; &amp; &amp; &amp; \left( \text{premium} \times \text{1.75}\right) &amp; &amp; \\
\hline\\
0-1\,\text{year} &amp; {0-1000} &amp; \text{local-1} &amp; \text{north} &amp; {29} &amp; {51} &amp; {5+} &amp; {55}\\
&amp; &amp; &amp; &amp; &amp; &amp; {4} &amp; {45}\\
&amp; &amp; &amp; &amp; &amp; &amp; {3} &amp; {38.33}\\
&amp; &amp; &amp; &amp; &amp; &amp; {2} &amp; {30}\\
&amp; &amp; &amp; &amp; &amp; &amp; {1} &amp; {25}\\
&amp; &amp; &amp; &amp; &amp; &amp; {0} &amp; {0}\\
&amp; &amp; &amp; \text{east} &amp; {91} &amp; {159} &amp; {0} &amp; {55}\\
&amp; &amp; &amp; &amp; &amp; &amp; {1} &amp; {45}\\
&amp; &amp; &amp; &amp; &amp; &amp; {2} &amp; {38.33}\\
&amp; &amp; &amp; &amp; &amp; &amp; {3} &amp; {30}\\
&amp; &amp; &amp; &amp; &amp; &amp; {4} &amp; {25}\\
&amp; &amp; &amp; &amp; &amp; &amp; {5+} &amp; {0}\\
&amp; &amp; &amp; \text{central} &amp; {60} &amp; {105} &amp; {0} &amp; {55}\\
&amp; &amp; &amp; &amp; &amp; &amp; {1} &amp; {45}\\
&amp; &amp; &amp; &amp; &amp; &amp; {2} &amp; {38.33}\\
&amp; &amp; &amp; &amp; &amp; &amp; {3} &amp; {30}\\
&amp; &amp; &amp; &amp; &amp; &amp; {4} &amp; {25}\\
&amp; &amp; &amp; &amp; &amp; &amp; {5+} &amp; {0}\\
&amp; &amp; &amp; \text{south} &amp; {71} &amp; {125} &amp; {0} &amp; {55}\\
&amp; &amp; &amp; &amp; &amp; &amp; {1} &amp; {45}\\
&amp; &amp; &amp; &amp; &amp; &amp; {2} &amp; {38.33}\\
&amp; &amp; &amp; &amp; &amp; &amp; {3} &amp; {30}\\
&amp; &amp; &amp; &amp; &amp; &amp; {4} &amp; {25}\\
&amp; &amp; &amp; &amp; &amp; &amp; {5+} &amp; {0}\\
&amp; &amp; &amp; \text{east Msia} &amp; {45} &amp; {80} &amp; {0} &amp; {55}\\
&amp; &amp; &amp; &amp; &amp; &amp; {1} &amp; {45}\\
&amp; &amp; &amp; &amp; &amp; &amp; {2} &amp; {38.33}\\
&amp; &amp; &amp; &amp; &amp; &amp; {3} &amp; {30}\\
&amp; &amp; &amp; &amp; &amp; &amp; {4} &amp; {25}\\
&amp; &amp; &amp; &amp; &amp; &amp; {5+} &amp; {0}\\
\vdots &amp; \vdots &amp; \vdots &amp; \vdots &amp; &amp; \vdots &amp; \vdots &amp; \vdots\\\\
\hline
\end{array}
\end{matrix}
\]</span></p>
<p><strong>FURTHER READING AND REFERENCES:</strong></p>
<p>Aitkin, M., Anderson, D., Francis, B., Hinde, J. 1990. <em>Statistical Modelling in GLIM</em>. New York: Oxford University Press.</p>
<p>Ajne, B. 1975. A note on the multiplicative ratemaking model. <em>ASTIN Bulletin</em> 8(2): 144-153.</p>
<p>Anderson, D., Feldblum, S., Modlin, C., Schirmacher, D., Schirmacher, E., Thandi, N. 2004. A practitioner's guide to Generalized Linear Models. <em>Casualty Actuarial Society Discussion Paper Program</em> 1-115.</p>
<p>Bailey, R.A. 1963. Insurance rates with minimum bias. <em>Proceedings of the Casualty Actuarial Society</em> 50(93): 4-14.</p>
<p>Bailey, R.A., Simon, L.J. 1960. Two studies in automobile insurance ratemaking. <em>ASTIN Bulletin</em> 49(1): 192-217.</p>
<p>Bichsel, F. 1964. Erfahrungs-Tarifierung in der Motorfahrzeug-halfplichtversicherung. <em>Milleilungen der Vereinigung Schweizerischer Versicherungsmathematiker</em> 119-129.</p>
<p>Boucher, J.P., Denuit, M., Guillen, M. 2007. Risk classification for claim count: a comparative analysis of various zero-inflated mixed Poisson and hurdle models. <em>North American Actuarial Journal</em> 11(4): 110-131.</p>
<p>Brockmann, M.J., Wright, T.S. 1992. Statistical motor rating: making effective use of your data<em>. Journal of the Institute of Actuaries</em> 119(3): 457-543.</p>
<p>Brown, R.L. 1988. Minimum bias with generalized linear models. <em>Proceedings of the Casualty Actuarial Society</em> 75(143): 187-217.</p>
<p>Bühlmann, H. 1964. Optimale Prämienstufen systeme. <em>Milleilungen der Vereinigung Schweizerischer Versicherungsmathematiker</em> 193-213.</p>
<p>Cameron, A.C., Trivedi, P.K. 1986. Econometric models based on count data: comparisons and applications of some estimators and tests. <em>Journal of Applied Econometrics</em> 1: 29-53.</p>
<p>Cameron, A.C., Trivedi, P.K. 1998. <em>Regression Analysis of Count Data</em>. New York: Cambridge University Press.</p>
<p>Chamberlain, C. 1980. Relativity pricing through analysis of variance. <em>Casualty Actuarial Society Discussion Paper Program</em> 4-24.</p>
<p>Corlier, F., Lemaire, J., &amp; Muhokolo, D. (1979). Simulation of an automobile portfolio. <em>The Geneva Papers on Risk and Insurance Theory 4</em>:40-46.</p>
<p>Coutts, S.M. 1984. Motor insurance rating, an actuarial approach. <em>Journal of the Institute of Actuaries</em> 111: 87-148.</p>
<p>Delaporte, P. 1965. Tarification du risque individuel d’accidents par la prime modelil ée sur le risqué. <em>ASTIN Bulletin</em> 3: 251-271.</p>
<p>Denuit, M., Marechal, X., Pitrebois, S., Walhin, J.F. 2007. <em>Actuarial Modeling of Claim Counts: Risk Classification, Credibility and Bonus-Malus Systems</em>. John Wiley and Sons: England.</p>
<p>Dionne, G., &amp; Vanasse, C. (1989). A generalization of automobile insurance rating models: the negative binomial distribution with a regression component. <em>ASTIN Bullettin 19</em>(2): 199-212.</p>
<p>Frangos, N. E., Vrontos, S. D. 2001. Design of optimal bonus-malus systems with a frequency and severity component on an individual basis in automobile insurance. <em>ASTIN Bulletin 31</em>(1): 1-22.</p>
<p>Harrington, S.E. 1986. Estimation and testing for functional form in pure premium regression models. <em>ASTIN Bulletin</em> 16: 31-43.</p>
<p>Hastings, N.A.J. 1976. Optimal claiming on vehicle insurance. <em>Operational Research Quarterly</em> 27: 805-813.</p>
<p>Hilbe, J. 2007. <em>Negative Binomial Regression</em>. Cambridge, UK: Cambridge University Press.</p>
<p>Ismail, N., Jemain, A.A. 2005. Bridging minimum bias and maximum likelihood methods through weighted equation. <em>Casualty Actuarial Society Forum</em> Spring: 367-394.</p>
<p>Ismail, N., Jemain, A.A. 2007. Handling overdispersion with negative binomial and generalized Poisson regression models. <em>Casualty Actuarial Society Forum</em> Winter: 103-158.</p>
<p>Ismail, N., Zamani, H. 2013. <strong>Estimation of claim count data using negative binomial, generalized Poisson, zero-inflated negative binomial and zero-inflated generalized Poisson regression models.</strong> <em>Casualty Actuarial Society E-Forum</em> Spring: 1-29.</p>
<p>Jung, J. 1968. On automobile insurance ratemaking. <em>ASTIN Bulletin</em> 5(1): 41-48.</p>
<p>Kolderman, J., Volgenant, A. 1985. Optimal claiming in an automobile insurance system with bonus-malus structure. <em>Journal of the Operational Research Society</em> 36: 239-247.</p>
<p>Lawless, J.F. 1987. Negative binomial and mixed Poisson regression. <em>Canadian Journal of Statistics</em> 15(3): 209-225.</p>
<p>Lemaire, J. 1976. Driver versus company, optimal behaviour of the policy holder. <em>Scandinavian Actuarial Journal</em> 59: 209-219<em>.</em></p>
<p>Lemaire, J. 1977. La soif du bonus. <em>ASTIN Bulletin</em> 9: 181-190.</p>
<p>Lemaire, J. 1979. How to define a Bonus-Malus system with an exponential utility function. <em>ASTIN Bulletin</em> 10: 274-282.</p>
<p>Lemaire, J., Zi, H.M. 1994. A comparative analysis of 30 Bonus-Malus systems. <em>ASTIN Bulletin</em> 24: 287-309.</p>
<p>Lemaire, J. 1998. Bonus-Malus systems: The European and Asian approach to merit-rating. <em>North American Actuarial Journal 2</em>(1): 26-38.</p>
<p>Loimaranta, K. 1972. Some asymptotic properties of bonus systems. <em>ASTIN Bulletin</em> 6: 233-245.</p>
<p>McCullagh, P., Nelder, J.A. 1989. <em>Generalized Linear Models (2nd Edition).</em> Chapman and Hall: London.</p>
<p>Morillo, I., Bermúdez, L. 2003. Bonus–malus system using an exponential loss function with an inverse Gaussian distribution. <em>Insurance: Mathematics and Economics 33</em>: 49-57.</p>
<p>Pitrebois, S., Denuit, M., Walhin, J.F. 2003. Fitting the Belgian Bonus-Malus system. <em>Belgian Actuarial Bulletin</em> 3(1): 58-62.</p>
<p>Renshaw, A.E., 1994. Modelling the claims process in the presence of covariates. <em>ASTIN Bulletin</em> 24(2): 265-285.</p>
<p>Tremblay, L. 1992. Using the Poisson inverse Gaussian in Bonus-Malus systems. <em>ASTIN Bulletin 22</em>(1): 97-106.</p>
<p>Vepsäläinen, S. 1972. Applications to a theory of bonus systems. <em>ASTIN Bulletin</em> 6: 212-221.</p>
<p>Walhin, J. F., Paris, J. 1999. Using mixed Poisson processes in connection with Bonus-Malus systems. <em>ASTIN Bulletin 29</em>(1): 81-99.</p>
<p>Winkelmann, R. 2008. <em>Econometric Analysis of Count Data</em>. Heidelberg: Springer Verlag.</p>
<p>Zamani, H., Ismail, N. 2012. Functional form for the generalized Poisson regression model. <em>Communications in Statistics (Theory and Methods)</em> 41(20): 3666–3675.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="C-LossReserves.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="C-DataSystems.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": ["LossDataAnalytics.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
