<!-- ###  Heterogeneous Risks {#S:HeterogeneousRisks} -->

As was noted in Section \@ref(S:IntroductionRatemaking), there are many variations in the risks being insured, the features of the contracts, and the people being insured. As an example, you might have a twin brother or sister who works in the same town and earns a roughly similar amount of money. Still, when it comes to selecting choices in rental insurance to insure contents of your apartment, you can imagine differences in the amount of contents to be insured, choices of deductibles for the amount of risk retained, and perhaps different levels of uncertainty given the relative safety of your neighborhoods. People, and risks that they insure, are different. 

When thinking about a collection of different, or *heterogenous*, risks, one option is to price all risks the same. This is common, for example, in government sponsored programs for flood or health insurance. However, as described in Section \@ref(S:PricingPrinciples), it is also common to have different prices, where the differences are commensurate with the risk being insured.


### Exposure to Risk {#S:ExposureToRisk}

One easy way to make heterogeneous risks comparable is through the concept of an **exposure**. To explain exposures, let us use *scale distributions* that we learned about in Chapter 3. To recall a scale distribution, suppose that $X$ has a parametric distribution and define a rescaled version $R = X/E$, $E > 0$. If $R$ is in the same parametric family as $X$, then the distribution is said to be a *scale distribution*. As we have seen, the gamma, exponential, and Pareto distributions are examples of scale distributions.

Intuitively, the idea behind exposures is to make risks more comparable to one another. For example, it may be that risks $X_1, \ldots, X_n$ come from different distributions and yet, with the choice of the right exposures, the rates $R_1, \ldots, R_n$ come from the same distribution. Here, we interpret the rate $R_i = X_i/E_i$ to be the loss divided by exposure.

[Table 7.1] provides a few examples. We remark that this table refers to "earned" car and house years, concepts that will be explained in Section \@ref(S:TrendDevelopment).

<a id=tab:7.1></a> 

[Table 7.1]: \#tab:7.1

$$
\small{
\begin{matrix}
\begin{array}{ll}
\text{Type of Insurance} & \text{Exposure Basis} \\\hline
\text{Personal Automobile} &  \text{Earned Car Year, Amount of Insurance Coverage} \\
\text{Homeowners} &  \text{Earned House Year, Amount of Insurance Coverage}\\
\text{Workers Compensation}  & \text{Payroll}\\
\text{Commercial General Liability} &  \text{Sales Revenue, Payroll, Square Footage, Number of Units}\\
\text{Commercial Business Property}  & \text{Amount of Insurance Coverage}\\
\text{Physician's Professional Liability}  & \text{Number of Physician Years}\\
\text{Professional Liability}  & \text{Number of Professionals (e.g., Lawyers or Accountants)}\\
\text{Personal Articles Floater} &  \text{Value of Item} \\
  \hline
\end{array}
\end{matrix}
}
$$

[Table 7.1] : Commonly used Exposures in Different Types of Insurance

An **exposure** is a type *rating factor*, a concept that we define explicitly in the next Section \@ref(S:RatingFactors). 
It is typically the most important rating factor, so important that both premiums and losses are quoted on a "per exposure" basis. 

For frequency and severity modeling, it is customary to think about the frequency aspect as proportional to exposure and the severity aspect in terms of loss per claim (not dependent upon exposure). However, this does not cover the entire story. For many lines of business, it is convenient for exposures to be proportional to inflation. Inflation is typically viewed as unrelated to frequency but proportional to severity.


#### Criteria for Choosing an Exposure  {-}

An exposure base should meet the following criteria. It should:

- be an accurate measure of the quantitative exposure to loss
- be easy for the insurer to determine (at the time the policy is calculated) and not subject to manipulation by the insured,
- be easy to understand by the insured and to calculate by the insurer,
- consider any preexisting exposure base established within the industry, and
- for some lines of business, it is proportional to inflation. In this way, rates are not sensitive to the changing value of money over time as these changes are captured in exposure base.


To illustrate, consider personal automobile coverage. Instead of the exposure basis "earned car year," a more accurate measure of the quantitative exposure to loss might be number of miles driven. However, this measure is difficult to determine at the time the policy is issued and subject to potential manipulation by the insured.

As another example, the exposure measure in commercial business property, e.g. fire insurance, is typically the amount of insurance coverage. As property values grow with inflation, so will the amount of insurance coverage. Thus, rates quoted on a per amount of insurance coverage are less sensitive to inflation than otherwise.

**Example: Workers' Compensation.** (*This example is from @werner2010basic . Probably too much institutional detail for this book. Still, a good placeholder.*) Consider the following example presented by Bouska (1989). Think of two construction firms, where one is unionized and the other is not. Assume that these two firms have the same number of employees who perform the same type of work and have similar number and type of loss experience. If the unionized company pays more per employee, then it will have a higher payroll. Assuming that payroll is the exposure basis for workers' compensation coverage, it will pay more for its coverage even though the loss experience is similar between the two firms. On the one hand, this is appropriate if losses are primarily due to indemnification to employees from lost salary due to not working from covered workers' accidents. On the other hand, this is inappropriate if losses are primarily due to medical payments that should be less related to the amount a person earns.

As a practical matter, this inequity was not as important when there were limits on payroll as an exposure base. However, Bouska (1989) cites the changes in the 1980's in the US where there was a movement to unlimited payrolls. Some groups proposed using a combination of hours worked and payroll as an exposure base. In contrast, the national rating bureau (National Council on Compensation Insurance, NCCI) wanted to use unlimited payroll because it is (a) easy to verify and (b) it moves naturally with inflation (thus reducing the need for annual rate revisions).

***

### Rating Factors {#S:RatingFactors}

A **rating factor**, or rating variable, is simply a characteristic of the policyholder or risk being insured by which rates vary. For example, when you purchase auto insurance, it is likely that the insurer has rates that differ by age, gender, type of car and where it is garaged, accident history, and so forth. These variables are known as rating factors. Although some of the variables are continuous, such as age, many if not most of them are categorical - *factor* is a label that is used for categorical variables. In fact, even with continuous variables such as age, it is common to categorize them by creating groups such as "young," "intermediate," and "old" for rating purposes. 

[Table 7.2] provides just a few examples. In many jurisdictions, the personal insurance market (e.g., auto and homeowners) is very competitive - using 10 or 20 variables for rating purposes is not uncommon.

<a id=tab:7.2></a> 

[Table 7.2]: \#tab:7.2

$$
\small{
\begin{matrix}
\begin{array}{l|l}\hline
\text{Type of Insurance} & \text{Rating Factors}\\\hline\hline
\text{Personal Automobile}  & \text{Driver Age and Gender, Model Year, Accident History}\\
\text{Homeowners}  & \text{Amount of Insurance, Age of Home, Construction Type}\\
\text{Workers Compensation}  & \text{Occupation Class Code}\\
\text{Commercial General Liability}  & \text{Classification, Territory, Limit of Liability}\\
\text{Medical Malpractice}  & \text{Specialty, Territory, Limit of Liability}\\
\text{Commercial Automobile}  & \text{Driver Class, Territory, Limit of Liability}\\
  \hline
\end{array}
\end{matrix}
}
$$
[Table 7.2] : Commonly used Rating Factors in Different Types of Insurance


***

**Example. Losses and Premium by Amount of Insurance and Territory.** To illustrate, [Table 7.3] presents a small fictitious data set from Chapter 9 of @werner2010basic. The data consists of loss and loss adjustment expenses (*LossLAE*), decomposed by three levels of *AOI*, amount of insurance, and three territories (*Terr*). For each combination of *AOI* and *Terr*, we also have available the number of policies issued, given as the *Exposure*.

<a id=tab:7.3></a> 

[Table 7.3]: \#tab:7.3

$$
\small{
\begin{matrix}
\begin{array}{cc|rrr}
\hline
       AOI &       Terr &   Exposure &    LossLAE &    Premium \\\hline
       \text{Low} &          1 &          7 &     210.93 &     335.99 \\
    \text{Medium} &          1 &        108 &   4,458.05 &   6,479.87 \\
      \text{High} &          1 &        179 &  10,565.98 &  14,498.71 \\\hline
       \text{Low} &          2 &        130 &   6,206.12 &  10,399.79 \\
    \text{Medium} &          2 &        126 &   8,239.95 &  12,599.75 \\
      \text{High} &          2 &        129 &  12,063.68 &  17,414.65 \\\hline
       \text{Low} &          3 &        143 &   8,441.25 &  14,871.70 \\
    \text{Medium} &          3 &        126 &  10,188.70 &  16,379.68 \\
      \text{High} &          3 &         40 &   4,625.34 &   7,019.86 \\
      \hline
       \text{Total}    &       & 988 &  65,000.00 &     99,664.01   \\\hline
\hline
\end{array}
\end{matrix}
}
$$
[Table 7.3] : Losses and Premium by Amount of Insurance and Territory

In this case, the rating factors *AOI* and *Terr* produce nine cells. Note that one might combine the cell "territory one with a low amount of insurance"" with another cell because there are only 7 policies in that cell. Doing so is perfectly acceptable - considerations of this sort is one of the main jobs of the analyst. An outline on selecting variables is in Section \@ref(S:SelectingRateFactors). Alternatively, you can also think about reinforcing information about the cell (*Terr* 1, Low *AOI*) by "borrowing" information from neighboring cells (e.g., other territories with the same *AOI*, or other amounts of *AOI* within *Terr* 1). This is the subject of **credibility** that is introduced in **Chapter 9**.

***

To understand the impact of rating factors, it is common to use relativities. A **relativity** is the difference of the expected risk between a specific level of a rating factor and an accepted baseline value. In this book, we work with relativities defined through ratios; it is also possible to define relativities through differences. Thus, our relativity is defined as

$$
\text{Relativity}_j = \frac{\text{(Loss/Exposure)}_j}{\text{(Loss/Exposure)}_{Base}} .
$$

***

**Example. Losses and Premium by Amount of Insurance and Territory - Continued.** Traditional classification methods consider only one classification variable at a time - they are univariate. Thus, if we wanted relativities losses and expenses (*LossLAE*) by amount of insurance, we might sum over territories to get the information displayed in [Table 7.4].

<a id=tab:7.4></a> 

[Table 7.4]: \#tab:7.4

$$
\small{
\begin{matrix}
\begin{array}{c|rrrr}
\hline
       AOI &   Exposure &    LossLAE & Loss/Exp &Relativity \\\hline
       \text{Low} &        280 &    14858.3 &   53.065   &0.835 \\
    \text{Medium} &        360 &    22886.7 &    63.574  &1.000 \\
      \text{High} &        348 &      27255.0 &   78.319  & 1.232 \\\hline
       \text{Total}    &        988 &  65,000.0 &            \\\hline
\hline
\end{array}
\end{matrix}
}
$$

[Table 7.4] : Losses and Relativities by Amount of Insurance

Thus, for example, losses and expenses per unit of exposure are 23.2% higher for risks with a high amount of insurance compared to those with a medium amount.  These relativities do not control for territory.

***

The introduction of rating factors allows the analyst to create cells that define small collections of risks -- the goal is to choose the right combination of rating factors so that all risks within a cell may be treated the same. In statistical terminology, we want all risks within a cell to have the same distribution (subject to rescaling by an exposure variable). This is the foundation of insurance pricing. All risks within a cell have the same price yet risks from different cells may have different prices. 

Said another way, insurers are allowed to charge different rates for different risks; *discrimination* of risks is legal and routinely done. Nonetheless, the basis of discrimination, the choice of risk factors, is the subject of extensive debate. This actuarial community, insurance management, regulators, and consumer advocates are all active participants in this debate. In addition to statistical criteria for assessing the significance of a rating factor, analysts much pay attention to business concerns of the company (e.g., is it expensive to implement a rating factor?), social criteria (is a variable under the control of a policyholder?), legal criteria (are there regulations that prohibit the use of a rating factor such as gender?), and other societal issues. These questions are largely beyond the scope of this book that seeks to introduce analytics in the insurance industry. Nonetheless, because they are so fundamental to pricing of insurance, a brief overview is given in Technical Supplement Section \@ref(S:SelectingRateFactors).

