<!-- ###  Rate Factor Selection {#S:LossRatio} -->

***

*This may become a Technical Supplement for Chapter 8*.

***

A complete discussion of rating factor selection is beyond the scope of this book. In addition to technical analyses, you have to think carefully about the type of business (personal, commercial) as well as the regulatory landscape. Nonetheless, a broad overview of some key concerns may serve to ground the reader as one thinks about the pricing of insurance contracts.


#### Statistical Criteria {-}

From an analyst's perspective, the discussion starts with the statistical significance of a rating factor. If the factor is not statistically significant, then the variable is not even worthy of consideration for inclusion in a rating plan. The statistical significance is judged not only on an in-sample basis but also on how well it fares on an out-of-sample basis, as per our discussion in **Section 4.2.** 

It is common in insurance applications to have many rating factors. Handling multivariate aspects can be difficult with traditional univariate methods. Analysts employ techniques such as *generalized linear models*; *Section 8.4* provides references that introduce you to this topic from statistical and insurance perspectives.

Rating factors are introduced are use to create cells that contain similar risks. A rating group should be large enough to measure costs with sufficient accuracy. There is an inherent trade-off between theoretical accuracy and homogeneity

As an example, most insurers charge the same automobile insurance premiums for drivers between the ages of 30 and 50, not varying the premium by age. Presumably costs do not vary much by age, or cost variances are due to other identifiable factors.

#### Operational Criteria {-}

From a business perspective, statistical criteria only provide a starting point for discussions of potential inclusion of rating factors. Inclusion of a rating factor must also induce economically meaningful results. From an insured's perspective, if differentiation by a factor produces little change in a rate then it is not worth including. From an insurer's perspective, the inclusion of a factor should help segment the marketplace in a way that helps attract the business that they seek. For example, we introduce the *Gini* index in **Section 4.A** as one metric that insurers use to describe the financial impact of a rating variable.

Rating factors should also be objective, inexpensive to administer, and verifiable. For example, automobile insurance underwriters often talk of "maturity" and "responsibility" as important criteria for youthful drivers. Yet, these are difficult to define objectively and to apply consistently. As another example, in automobile it has long been known that amount of miles (or kilometers) driven is an excellent rating factor. However, insurers have been reluctant to adopt this factor because it is subject to abuse. Historically, driving mileage has not been used because of the difficulty in verifying this variable (it is far too easy to alter the car's odometer to change reported mileage). Going forward, modern day drivers and cars are equipped with global positioning devices and other equipment that allow insurers to use distance driven as a rating factor because it can be verified.


#### Rating Factors from the Perspective of a Consumer {-}

Insurance companies sell insurance products to a variety of consumers; consequently, companies are affected by public perception. 
On the one hand, free market competition dictates rating factors that insurers use, as is common in commercial insurance. On the other hand, insurance may be required by law. This is common in personal insurance such as third party automobile liability and homeowners. In these instances, the mandatory and de facto mandatory purchase of insurance may mean that free market competition is insufficient to protect policyholders. Here, the following items affect the social acceptability of using a particular risk characteristic as a rating variable:

- Affordability - introduction of some variables may be mitigated by resulting high costs of insurance. 
- Causality - other things being equal, a rating variable is easier to justify if there is a "causal" relationship with losses. A good example is the effects of smoking in life insurance. For many years, this factor was viewed with suspicion by the industry. However, over time, scientific evidence provided overwhelming evidence as this an important predictor of mortality.
- Controllability - A controllable variable is one that is under the control of the insured, e.g., installing burglar alarms. The use of controllable rating variables encourages accident prevention.
- Privacy concerns - people are reluctant to disclose personal information. In today's world with increasing emphasis on social media and the availability of personal information, consumer advocates are concerned that the benefits of big data skew heavily in insurers' favor. They reason that insureds do not have equivalent new tools to compare quality of coverage/policies and performance of insurance companies. 

**Example: 16-year old Drivers.** In some cases, a particular risk characteristic may identify a small group of insureds whose risk level is extremely high, and if used as a rating variable, the resulting premium may be unaffordable for that high-risk class. To
the extent that this occurs, companies may wish to or be required by regulators to combine classes and introduce subsidies. For example, 16-year-old drivers are generally higher risk than 17-year-old drivers. Some companies have chosen to use the same rates for 16- and 17-year-old drivers to minimize the affordability issues that arise when a family adds a 16-year-old to the auto policy.


#### Societal Effects of Rating Factors {-}

With public discussions of rating factors, it is also important to think about the societal effects of classification.

For example, does a rating variable encourage "good" behavior? As an example, we return to the use of distance driven as a rating factor. Many people advocate for including this variable as a factor. The motivation is that if insurance, like fuel, is priced based on distance driven, this will induce consumers to reduce the amount driven, thereby benefitting society.

Harrington/Niehaus discuss other aspects of societal effects of classification

- Re-distributive Effects - provide a cross-subsidy from e.g., high risks to low risks
- Classification Costs - Money spent by society, insurers, to classify people appropriately...


#### Legal Criteria {-}

For example, some states have statutes prohibiting the use of gender in rating insurance while others permit it as a rating variable. As a result, an insurer writing in multiple states may include gender as a rating variable in those states where it is permitted, but not include it in a state that prohibits its use for rating.

See the discussion in Section \@ref(S:RateRegulation).

If allowed by law, the company may continue to charge the average rate but utilize the characteristic to identify, attract, and select the lower-risk insureds that exist in the insured population; this is called *skimming the cream.*




