<!-- ###  Rate Regulation {#S:RateRegulation} -->

Insurance regulation helps to ensure the financial stability of insurers and to protect consumers. Insurers receive premiums in return for promises to pay in the event of a contingent (insured) event. Like other financial institutions such as banks, there is a strong public interest in promoting the continuing viability of insurers. 

<!-- Further, regulation is needed to protect consumers because: -->

<!-- a.	Insurance policies are complex legal documents that are often difficult to interpret and understand. -->
<!-- b.	Insurers write policies and sell them to the public on a "take it or leave it" basis. Personal insurance is not a contract where each party has equal access to information. With their resources, insurers are thought to have greater access to information about risks they are insuring than consumers. -->

#### Market Conduct {-}

<!-- One aspect of regulation is known as *market conduct* regulation - systems of regulatory controls that have been established requiring insurers to demonstrate that they are providing fair and reliable services, including product regulation. -->

To help protect consumers, regulators impose administrative rules on the behavior of market participants. These rules, known as `r Gloss('market conduct regulation')`, provide systems of regulatory controls that  require insurers to demonstrate that they are providing fair and reliable services, including rating, in accordance with the statutes and regulations of a jurisdiction. 

1. *Product regulation* serves to protect consumers by ensuring that insurance policy provisions are reasonable and fair, and do not contain major gaps in coverage that might be misunderstood by consumers and leave them unprotected.
2. The insurance product is the insurance contract (policy) and the coverage it provides. Insurance contracts are regulated for these reasons:
    a. Insurance policies are complex legal documents that are often difficult to interpret and understand.
    b. Insurers write insurance policies and sell them to the public on a "take it or leave it" basis.

Market conduct includes rules for *intermediaries* such as agents (who sell insurance to individuals) and brokers (who sell insurance to businesses). Market conduct also includes *competition policy regulation*, designed to ensure an efficient and competitive marketplace that offers low prices to consumers. 


#### Rate Regulation  {-}

*Rate regulation* helps guide the development of premiums and so is the focus of this chapter. As with other aspects of market conduct regulation, the intent of these regulations is to ensure that insurers not take unfair advantage of consumers. Rate (and policy form) regulation is common worldwide.

The amount of regulatory scrutiny varies by insurance product. Rate regulation is uncommon in life insurance. Further, in non-life insurance, most commercial lines and reinsurance are free from regulation. Rate regulation is common in automobile insurance, health insurance, workers compensation, medical malpractice, and homeowners insurance. These are markets in which insurance is mandatory or in which universal coverage is thought to be socially desirable.

There are three principles that guide rate regulation: rates should

* be adequate (to maintain insurance company solvency), 
* but not excessive (not so high as to lead to exorbitant profits), 
* nor unfairly discriminatory (price differences must reflect expected claim and expense differences). 

Recently, in auto and home insurance, the twin issues of availability and affordability, which are not explicitly included in the guiding principles, have been assuming greater importance in regulatory decisions.


#### Rates are Not Unfairly Discriminatory  {-}

<!-- In general, government regulation of insurance rates takes on one of two forms: -->

<!-- 1. Regulations that restrict the amount, or level, of premium rates, and -->
<!-- 2. Regulations that restrict the type of information that can be used in risk classification. -->

<!-- The following section, on types of insurance regulations, focuses on the amount of insurance rates. For the second, let us return to the guiding principles for insurance rate regulation. The first two of these three guiding principles, that rates be adequate but not excessive, are reasonably intuitive. The third, that rates not be unfairly discriminatory, requires a bit more explanation. -->


Some government regulations of insurance restrict the amount, or level, of premium rates. These are based on the first two of the three guiding rate regulation principles, that rates be adequate but not excessive. This type of regulation is discussed further in the following section on types of rate regulation.

Other government regulations restrict the type of information that can be used in risk classification. These are based on the third guiding principle, that rates not be unfairly discriminatory. "Discrimination" in an insurance context has a different meaning than commonly used; for our purposes, discrimination means the ability to distinguish among things or, in our case, policyholders. The real issue is what is meant by the adjective "fair."

In life insurance, it has long been held that it is reasonable and fair to charge different premium rates by age. For example, a life insurance premium differs dramatically between an 80 year old and someone aged 20. In contrast, it is unheard of to use rates that differ by:

- ethnicity/race,
- political affiliation, or
- religion.

It is not a matter of whether data can be used to establish statistical significance among the levels of any of these variables. Rather, it is a societal decision as to what constitutes notions of "fairness."

Different jurisdictions have taken different stances on what constitutes a fair rating variable. For example, in some juridictions for some insurance products, gender is no longer a permissible variable. As an illustration, the European Union now prohibits the use of gender for automobile rating. As another example, in the U.S., many discussions have revolved around the use of credit ratings to be used in automobile insurance pricing. 
Credit ratings are designed to measure consumer financial reponsibility. Yet, some argue that credit rates are good proxies for ethnicity and hence should be prohibited.

In an age where more data is being used in imaginative ways, discussions of what constitutes a fair rating variable will only become more important going forward and much of that discussion is beyond the scope of this text. However, it is relevant to the discussion to remark that actuaries and other data analysts can contribute to societal discussions on what constitutes a "fair" rating variable  in unique ways by establishing the magnitude of price differences when using variables under discussion.

<!-- Should we collect these variables? -->

<!-- - Sometimes no. Just the act of collecting them means that we may become biased in subtle ways, a type of moral hazard. -->
<!-- - Sometimes yes. Either the status is uncertain or we may wish to understand their effects and prove that we are not being biased. -->


#### Types of Rate Regulation  {-}

There are several methods, that vary by the level of scrutiny, by which regulators may restrict the rates that insurers offer.

The most restrictive is a `r Gloss('government prescribed')` regulatory system, where the government regulator determines and promulgates the rates, classifications, forms, and so forth, to which all insurers must adhere. Also restrictive are `r Gloss('prior approval')` systems. Here, the insurer must file rates, rules, and so forth, with government regulators. Depending on the statute, the filing becomes effective when a specified waiting period elapses (if the government regulator does not take specific action on the filing, it is deemed approved automatically) or when the government regulator formally approves the filing.

The least restrictive is a `r Gloss('no file')` or *record maintenance* system where the insurer need not file rates, rules, and so forth, with the government regulator. The regulator may periodically examine the insurer to ensure compliance with the law. Another relatively flexible system is the `r Gloss('file only')` system, also known as *competitive* rating, where the insurer simply keeps files to ensure compliance with the law.

In between these two extremes are the (1) file and use, (2) use and file, (3) modified prior approval, and (4) flex rating systems.

1. File and Use: The insurer must file rates, rules, and so forth, with the government regulator. The filing becomes effective immediately or on a future date specified by the filer.
2. Use and File: The filing becomes effective when used. The insurer must file rates, rules, and so forth, with the government regulator within a specified time period after first use.
3. Modified Prior Approval: This is a hybrid of "prior approval" and "file and use" laws. If the rate revision is based solely on a change in loss experience then "file and use" may apply. However, if the rate revision is based on a change in expense relationships or rate classifications, then "prior approval" may apply. 
4. Flex (or Band) Rating: The insurer may increase or decrease a rate within a "flex band," or range, without approval of the government regulator. Generally, either "file and use" or "use and file" provisions apply.

***

For a broad introduction to government insurance regulation from a global perspective, see  the website of the [International Association of Insurance Supervisors (IAIS)](https://www.iaisweb.org/home).