

```{r eval = INSTALLPACKAGES, echo = FALSE}
#  Here are packages required for all book chapters
install.packages("actuar")
install.packages("alabama")
install.packages("epitools")
install.packages("GB2")
install.packages("pander")
install.packages("VGAM")
# Install bookdown if you want to compile the whole book
#install.packages("bookdown")

```


<p style="text-align:right;">
*Date of this draft*: `r today <- Sys.Date();format(today, format="%d %B %Y")`</p>

<script language="javascript">
function toggle(id1,id2) {
	var ele = document.getElementById(id1); var text = document.getElementById(id2);
	if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Solution";}
		else {ele.style.display = "block"; text.innerHTML = "Hide Solution";}}
</script>
<script language="javascript">
function togglecode(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show R Code";}
      else {ele.style.display = "block"; text.innerHTML = "Hide R Code";}}
</script>
<script language="javascript">
function toggleEX(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Example";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Example";}}
</script>
<script language="javascript">
function toggleTheory(id1,id2) {
   var ele = document.getElementById(id1); var text = document.getElementById(id2);
   if (ele.style.display == "block") {ele.style.display = "none"; text.innerHTML = "Show Theory";}
      else {ele.style.display = "block"; text.innerHTML = "Hide Theory";}}
</script>

<!-- Sample code to be added at the beginning of the chapter -->

<!-- # --- -->
<!-- # title: Chapter from Loss Data Analytics -->
<!-- # output: -->
<!-- #   html_document: -->
<!-- #     toc: yes -->
<!-- #     toc_depth: '3' -->
<!-- #     number_sections: yes -->
<!-- # #  pdf_document: -->
<!-- # #    number_sections: yes -->
<!-- # #    toc: yes -->
<!-- # #    toc_depth: '3' -->
<!-- # --- -->
<!-- #  -->
<!-- # ```{r echo = FALSE} -->
<!-- # INSTALLPACKAGES <- FALSE -->
<!-- # # Remove the hashtag (#) if you want to install packages -->
<!-- # #INSTALLPACKAGES <- TRUE -->
<!-- # ``` -->
<!-- #  -->
<!-- # ```{r child = 'HeaderCode.Rmd'} -->
